### ISSUE TITLE
Make source locations more generic.

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#10]
So having all my posts in `_posts` is nice but what if I'd like them to be in `blog`? Also, what if I want to generate an `about.html`?

Maybe we should take a more generic approach of compiling all `.tpl` files, no matter where they are (or, better, allow the user to specify the file ending template files should have).

**Comment by tak1n** [comment]
Also YAML is now available: https://github.com/chyh1990/yaml-rust

**Comment by johannhof** [comment]
Continues at #37
