### ISSUE TITLE
Clean command

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/cobalt.rs#102]
We should add a command that will recursively remove the `dest` directory.

**Comment by johannhof** [comment]
Mmh since you have to specify the dest directory it wouldn't be much different from `rm -rf` right? If this is so easy to solve maybe we shouldn't make the effort of implementing and maintaining the same functionality :)

**Comment by LucioFranco** [comment]
I was thinking for sites that have the `dest` in the `cobalt.yml` file they can just run clean and it will make the git dir clean for example.
