### ISSUE TITLE
Include templates extend or smart include for the layouts

### ISSUE THREAD

**Issue by jespino** [cobalt-org/cobalt.rs#104]
Currently the layouts are on liquid have to been rewritten various times when you want to define different layouts. Could be nice to have a "extends" tag like in django templates or jinja. or something that allow to build a template from a base template.

I think can be realtively easy to implement a tag like:

**base.liquid**

```
<html>
  <body>
    {{include_block}}
  </body>
</html>
```

**default.liquid**

```
{% include "file" block_var="include_block" %}
  <h1>Posts</h1>
  <div>{{ content }}</div>
{% endinclude %}
```

**Comment by LucioFranco** [comment]
I think this is more a [liquid](https://github.com/cobalt-org/liquid-rust) issue than a cobalt. Correct me if I am wrong @johannhof.

**Comment by LucioFranco** [comment]
I'm going to close this as I moved the issue to [cobalt-org/liquid-rust#36](https://github.com/cobalt-org/liquid-rust/issues/36).
