### ISSUE TITLE
Move from Nickel to Hyper

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/cobalt.rs#109]
Nickel is a huge library and it would be nicer to move to a more lightweight web server. We just need to serve files so we could just open the file and dump the bytes into the response. Let me know if you guys see any issues with this.

**Comment by johannhof** [comment]
Yeah, I agree. It's not really a matter of binary size as the compilation should eliminate the code we're not using but rather the installation experience which involves installing all the nickel dependencies, and that's a drag.
