### ISSUE TITLE
install.sh fails

### ISSUE THREAD

**Issue by patxipierce** [cobalt-org/cobalt.rs#1120]
Hello,

Just dropped by to say in my debian 11 install, this install command fails.

````
curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs --crate cobalt

install.sh: GitHub repository: https://github.com/cobalt-org/cobalt.rs
install.sh: Crate: cobalt
install.sh: Tag: latest ()
install.sh: Target: x86_64-unknown-linux-gnu
install.sh: Installing to: /home/pxi/.cargo/bin

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
````

I think its because

`curl -s "https://github.com/cobalt-org/cobalt.rs/latest" | cut -d'"' -f2 | rev | cut -d'/' -f1 | rev`

returns:
`Not Found`

However this command worked:

`curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs --crate cobalt --tag "v0.18.3"`

**Comment by epage** [comment]
Sorry, this fell through the cracks.  japaric's install script seems to be unmaintained.  You can find a fixed version at https://raw.githubusercontent.com/crate-ci/gh-install/master/v1/install.sh

The docs have been updated to reflect this
