### ISSUE TITLE
Coverage issue

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/cobalt.rs#114]
For some reason coveralls has been reporting the wrong coverage.

**Comment by johannhof** [comment]
I think it's now including the main.rs file which is of course not covered using the unit and integration tests that talk to the API directly.

There's an option in travis-cargo coverage to exclude by pattern, maybe we could use that.

**Comment by LucioFranco** [comment]
I excluded the main file. It has jumped to 72% but it seems to have lost line coverage in the `error.rs` file.

**Comment by johannhof** [comment]
This has been improved by #176 , although coverage is still not perfect.
