### ISSUE TITLE
cobalt import adds ".git" into commit

### ISSUE THREAD

**Issue by kstep** [cobalt-org/cobalt.rs#117]
When I run `cobalt import` on my blog locally, it includes `.git` into commit.
The `.git` must never be included in any commits.

**Comment by LucioFranco** [comment]
Do you have any files ignored in your config?

**Comment by kstep** [comment]
I tried both ways: with and without ignored files.
Also, I tried to add `ignored` option to `.cobalt.yml` to no avail.

**Comment by LucioFranco** [comment]
So the only way `.git` could ever be imported is if it is being copied over to build folder. Could you paste your config with your `ignore` configured.

**Comment by kstep** [comment]
I build to the root directory of my project.
See https://github.com/kstep/kstep.github.com/ for the concrete setup.
So I build from source directory `_src` to root project directory.
Do you want to tell me I shouldn't do it?

**Comment by LucioFranco** [comment]
try adding this to your config:

```yaml
ignore:
  - .git/*
  - build/* # change this to your build folder name
```

**Comment by LucioFranco** [comment]
I am going to close this as this seems to have been solved.
