### ISSUE TITLE
Looks like 0.19.1 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [cobalt-org/cobalt.rs#1170]
👋 looks like 0.19.1 release was not completed (ie the release did not get marked as latest release), raise this issue for some awareness. Thanks! 🙏 

relates to https://github.com/Homebrew/homebrew-core/pull/164444

**Comment by epage** [comment]
Strange.  I can't tell why the post-release workflow didn't run.  I tagged a new release and the action triggered.

**Comment by epage** [comment]
That worked
