### ISSUE TITLE
Question about custom Collections (like: pages or categories)

### ISSUE THREAD

**Issue by matschundbrei** [cobalt-org/cobalt.rs#1178]
Hi there,

Is there any way to have additional collections for categories, tags, pages, etc?

Cheers,
J

PS: I successfully migrated an old PicoCMS to cobalt and I'm quite happy with the result, I just would've been faster if I did not have to write the navigation and the underlying data (pages, page-levels, categories, etc) completely from scratch.

**Comment by epage** [comment]
Custom collections is being tracked in #368.  Closing in favor of that.
