### ISSUE TITLE
Category add failure

### ISSUE THREAD

**Issue by harrymkt** [cobalt-org/cobalt.rs#1206]
Hello. How to add category support on my blog? I couldn't find any fully written documentation related to this.

Although I tried using tags as an example in the documentation, it does not work as expected, because I cannot access `paginator.pages` object as soon as I have the `include: Categories`.
<br>
categories.md

```Markdown
---
layout: default.liquid
title: Categories
permalink: /categories
pagination:
  include: Categories
  per_page: 5
  permalink_suffix: "./{{num}}/"
  order: Desc
  sort_by: ["published_date"]
---
{% if paginator.indexes %}
# Categories
{% for ptag in paginator.indexes %}
<a href="/{{ ptag.index_permalink }}/">{{ ptag.index_title }} ({{ ptag.total_pages }})</a>

{% endfor %}
{%else%}
# Blog
Here I will share my useful posts

## posts
{%for post in paginator.pages%}
{%assign posttitle=post.title%}
{%if post.description and post.description!=""%}
{%assign posttitle=posttitle | append: " (" | append: post.description | append: ")"%}
{%endif%}
### [{{posttitle}}](/{{post.permalink}})
Author: {{post.data.author}}

Published on: {{post.published_date | date: "%A, %B %d %Y at %r"}}, GMT+6:30

{{post.excerpt | strip_html}}

{%endfor%}
{%endif%}

{%if paginator.previous_index or paginator.next_index%}
## Pagination
{{paginator.index}} / {{paginator.total_indexes}}

{%if paginator.previous_index%}
[Previous page](/{{paginator.previous_index_permalink}})
{%endif%}

{%if paginator.next_index%}
[Next page](/{{paginator.next_index_permalink}})
{%endif%}

{%if paginator.previous_index%}
[First page](/{{paginator.first_index_permalink}})
{%endif%}

{%if paginator.next_index%}
[Last page](/{{paginator.last_index_permalink}})
{%endif%}
{%endif%}
```

And I have set `permalink: /{{parent}}/{{categories}}/{{name}}` in `posts.default` config.

**Comment by skierpage** [comment]
Yes, I find categories quite opaque. Besides more "theory of operation" documentation it would be great if `cobalt init` created a more flshed-out site that demonstrated cobalt features like categories and paginated "list of posts by date" index pages.

**Comment by harrymkt** [comment]
> Is there a web site using cobalt whose source is on the web that uses these features?

I have my website for normal pagination, that is, without categories. Reading time is also available to be determined. But my website is designed accessibility over visuals, because I am **blind**.

**Comment by epage** [comment]
> Yes, I find categories quite opaque. Besides more "theory of operation" documentation it would be great if cobalt init created a more flshed-out site that demonstrated cobalt features like categories and paginated "list of posts by date" index pages.

With scaffolding generation, there is always the trade off between teaching and getting in the way of the user getting up and going.

**Comment by epage** [comment]
Our end-to-end tests can also serve as examples
- Site with categories: https://github.com/cobalt-org/cobalt.rs/tree/master/tests/cmd/pagination_categories.in
- What gets generated: https://github.com/cobalt-org/cobalt.rs/tree/master/tests/cmd/pagination_categories.out/_dest

**Comment by harrymkt** [comment]
@epage Thanks, it helps!
