### ISSUE TITLE
Draft support

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#121]
It would be great to have support for either a _drafts folder or, even better, a `draft: true` attribute in front matter.

**Comment by LucioFranco** [comment]
What would be the benefit of this? Why could someone not add a drafts folder and just add that to the ignore field in the config?

**Comment by johannhof** [comment]
With a drafts folder you could run `cobalt build --drafts` and have your drafts show up in the normal posts list.
