### ISSUE TITLE
Add no hyper feature

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/cobalt.rs#125]
It would be nice to add a `--feature no-hyper` so that you do not need to have `openssl` installed. I am having issues on windows getting `openssl` to link.

**Comment by johannhof** [comment]
Solved in 3e46f9cc2dce61f8f1420cb3d6b4411a2e0c17b2 by removing the ssl feature (which we don't need) from Hyper.

**Comment by LucioFranco** [comment]
@johannhof awesome! Great work. I will try and see if I can debug those appveyor issues on my windows computer.

**Comment by johannhof** [comment]
@LucioFranco appyeyor should be working now.

**Comment by LucioFranco** [comment]
@johannhof you are right, I did not notice! 😄 great work!
