### ISSUE TITLE
How to create or use plugins ?

### ISSUE THREAD

**Issue by ar-ms** [cobalt-org/cobalt.rs#127]
Hello everyone,

I have multiple question about plugins:
- Is it possible to use plugins ? Where to find them ?
- It is possible to create new plugin ? How to create them ?

In general, where can I find the documentation ?

**Comment by LucioFranco** [comment]
So at the moment #57 is still open. We have not found a good way yet to incorporate plugins. What  ideas do you have? It might be something we want to implement.

**Comment by ar-ms** [comment]
Oups I didn't see the #51 issue, I don't have any idea yet, I will analyze how the project works and propose ideas if I have :) ! Thank you for your response :smile: !

**Comment by LucioFranco** [comment]
No worries! If you have any ideas feel free to submit a PR! We always welcome help! I am going to close this as it's not an issue. Ping me on [gitter](https://gitter.im/cobalt-org/cobalt.rs) if you have any more questions.
