### ISSUE TITLE
Errors building site with post with templating code

### ISSUE THREAD

**Issue by freiguy1** [cobalt-org/cobalt.rs#133]
Hello there.  I'm attempting to switch my blog to use cobalt from ghost.  I have a post which contains this markdown:

```
<div class="container">
    <div class="row">
        {{#each children}}
            <div class="col-xs-6 col-sm-3 col-lg-2 dir-item">
                <a href="{{url}}">
                    <span class="icon-{{file_type}} icon"></span>
                    <span>{{name}}</span>
                </a>
            </div>
        {{/each}}
    </div>
</div>
```

So this snippet that I wanted to display actually had templating (handlebars templating to be specific) inside it.  `cobalt build` exited with an error when converting this markdown file to html. This behavior could be intentional so you could put dynamic-ish things in the post rather than just the liquid templates (i.e. post.liquid).  However, I needed to surround these pieces with `{% raw %}` ... `{% endraw %}` to stop `cobalt build` from breaking.  Perhaps cobalt should be breaking more gracefully in these cases with hints on how to fix it. Or it could be fixed by making the content of posts not be parsed as templates.

Thanks!
Ethan

**Comment by epage** [comment]
So let me see if I understand.  Inside of your markdown, you are trying to quote a block of HTML that is using handlebars templating?  Are you using ``` for quoting it?  And you are wanting Cobalt to improve its error reporting in this case?

Would you be able to provide a set of files to reproduce this with, what Cobalt's error looks like right now, and what your ideal error would look like?

**Comment by freiguy1** [comment]
Almost a year later, I'm going to try my blog switcherino initiative from ghost to cobalt.  I'll close this issue if I don't run into the issue again or add more details if I do have more problems.

**Comment by freiguy1** [comment]
I did get an error. Yep the markdown content of a post does contain some html surrounded by ```. Here's a snippet of that post:

```
Each time a directory is encountered, a corresponding directory and `index.html` file within that directory is created in the content website.  These `index.html` files use the template file located at `layouts/dir.hbs` in content. Mine looks like this at the moment:

\```
<div class="container">
    <div class="row">
        {{#each children}}
            <div class="col-xs-6 col-sm-3 col-lg-2 dir-item">
                <a href="{{url}}">
                    <span class="icon-{{file_type}} icon"></span>
                    <span>{{name}}</span>
                </a>
           </div>
        {{/each}}
    </div>
</div>
\``` 
 
This list called `children` you see in the above template is sorted with directories at first and then alphabetically.  The `file_type` property simply provides some javascript code information for getting the correct icon.
```

I put some back slashes in front of the ``` so the github issue formatter doesn't use them. Maybe there's a better way to escape them. The error I got is:

```
[error]  Parsing error: Expected |, found children
```

That's because i use the word `children` in my content.  Here's what I expect: no error, and that my html code inside ``` would not get parsed as liquid or markdown (i believe that's what's happening), but just be regular text.

Until next year! ;)

**Comment by epage** [comment]
> That's because i use the word children in my content. Here's what I expect: no error, and that my html code inside ``` would not get parsed as liquid or markdown (i believe that's what's happening), but just be regular text.

That would require markdown and liquid to know about each other.  What you probably want to do is surround your block with `{ raw }` and and `{ endraw }`.
https://shopify.github.io/liquid/tags/raw/

With just a single raw block, I doubt you'll run into liquid-rust/#79 but I want to note to so you can avoid wasting time debugging it.

**Comment by freiguy1** [comment]
Thanks @epage
