### ISSUE TITLE
Display file and location of liquid errors

### ISSUE THREAD

**Issue by shishkin** [cobalt-org/cobalt.rs#136]
I'm converting an octopress blog to cobalt and my experience so far is frustrating. Instead of running the whole thing through cobalt and fixing what breaks, I need to start from scratch and add line by line because when cobalt breaks I have no idea why.

It would be much nicer if instead of `[error]  Liquid error: Rendering error: Tried to iterate over None, which is not supported.` or something similarly unhelpful, cobalt would directly point to the problem.

**Comment by johannhof** [comment]
Yeah this is a much-needed feature. We'd probably have to patch up both liquid and Cobalt for this. But it's absolutely worth doing and sounds like an interesting project. I'll try to find out what it takes to get this done

Thanks for giving Cobalt a try. Sorry for the delay in responding, I was organizing a conference :)

**Comment by epage** [comment]
Create cobalt-org/liquid-rust#105 to help track the liquid part of this work.

**Comment by epage** [comment]
#291 gets us reporting of file name.

**Comment by epage** [comment]
I closed this in hopes that the extra error reporting context in #372 would be sufficient.  Otherwise, we'll probably need to wait on https://github.com/cobalt-org/liquid-rust/issues/138.
