### ISSUE TITLE
Minify CSS files upon build

### ISSUE THREAD

**Issue by ebkalderon** [cobalt-org/cobalt.rs#137]
When I'm iterating on a project, I like to have separate CSS files with human-readable indentation, but this can have a negative performance impact on deployment. It would be nice if Cobalt could "minify" my stylesheets when building, e.g. stripping whitespace and indentation, removing comments, merging the CSS into one file, etc. It would be even cooler if these parameters were configurable, too!

**Comment by ebkalderon** [comment]
Looks like this issue is related to (and may be a duplicate of) issue #108.

**Comment by epage** [comment]
We now have minify support
