### ISSUE TITLE
Get the content of a post

### ISSUE THREAD

**Issue by deontologician** [cobalt-org/cobalt.rs#138]
It would be nice to be able to get the individual contents of each post for some kind of main page feature. So like:

```liquid
{% for post in posts %}
<article>
  <h2>{{post.title}}</h2>
  {{post.content}}
</article>
{% endfor %}
```

**Comment by johannhof** [comment]
Yup this is a good idea. I wonder if this is trivial to do though, since the post rendering is pretty late in the pipeline and all documents get rendered in parallel.

**Comment by deontologician** [comment]
In jekyll I guess they have an extra "pagination" thing that enables this.
https://jekyllrb.com/docs/pagination/

**Comment by johannhof** [comment]
Actually since we recently separated rendering from file creation this 
might be easier than I thought. I'll give it a try!
