### ISSUE TITLE
Get next and previous posts

### ISSUE THREAD

**Issue by ebkalderon** [cobalt-org/cobalt.rs#139]
This is an important feature to have for any blog. See [this blog post by David Elbe](http://david.elbe.me/jekyll/2015/06/20/how-to-link-to-next-and-previous-post-with-jekyll.html) for its usage in Jekyll.

**Comment by johannhof** [comment]
Yup, would be nice.

**Comment by nott** [comment]
i'm woking on this

**Comment by ebkalderon** [comment]
@nott Any progress with this lately?

**Comment by epage** [comment]
Fixed by #218
