### ISSUE TITLE
Extending a layout has incorrect indentation

### ISSUE THREAD

**Issue by ebkalderon** [cobalt-org/cobalt.rs#141]
When extending from a layout template, the resulting HTML has inconsistent indentation. Imagine you have an example layout file `default.liquid` which looks like this:

``` liquid
<!doctype html>
<html>
    <head> ... </head>
    <body>
        {% if is_post %}
            {% include '_layouts/post.liquid' %}
        {% else %}
            {{ content }}
        {% endif %}
    </body>
</html>
```

and also a page which extends the layout:

``` liquid
extends: default.liquid

---
<section id="hero">
    <!-- blah blah -->
</section>
```

One would expect the resulting HTML generated by Cobalt to look like:

``` html
<!doctype html>
<html>
    <head> ... </head>
    <body>
        <section id="hero">
            <!-- blah blah -->
        </section>
    </body>
</html>
```

But instead, Cobalt generates this:

``` html
<!doctype html>
<html>
    <head> ... </head>
    <body>

<section id="hero">
    <!-- blah blah -->
</section>

    </body>
</html>
```

Not only is the page content pasted directly into the layout it extends from without any indentation whatsoever, there are also extra newlines around where the Liquid markup used to be. This doesn't break the functionality of the page in any way, but it still looks pretty ugly.

**Comment by epage** [comment]
Yeah, the results aren't pretty. Its even worse if you try to use an include in a <pre> or markdown block quotes.

Cobalt is using the Liquid template language.  Liquid has recently defined semantics for [removing whitespace](https://help.shopify.com/themes/liquid/basics/whitespace) but has not added semantics yet for perpetuating whitespace.  Adding support for [`capture`](https://help.shopify.com/themes/liquid/tags/variable-tags#capture) would at least allow us to support the documented workaround.

**Comment by epage** [comment]
If you don't mind, I've moved this issue over to liquid as cobalt-org/liquid-rust#106.

Its hard to say where is a better home.  This is specifically an issue with Liquid but someone contributing to cobalt doesn't really care if its liquid or cobalt.  Maybe I'll update CONTRIBUTING or something.
