### ISSUE TITLE
Does not build with 1.0

### ISSUE THREAD

**Issue by Liamsi** [cobalt-org/cobalt.rs#16]
Could you specify the toolchain you did the last successful build (and add it to rustle command in Readme.md)?

**Comment by tak1n** [comment]
Rustle uses the latest nightly per default.

I'm currently using: `rustc 1.2.0-nightly (f76d9bcfc 2015-05-28) (built 2015-05-28)`
Note I'm not using rustle, just using the rustup script from: www.rust-lang.org/install.html

**Comment by Liamsi** [comment]
Thank you for the prompt reply. Would you recommend to use nightly even if it works with 1.0.0?

**Comment by tak1n** [comment]
I would use nightly, but I'm still not sure why 1.0.0 works for you, because like in https://github.com/cobalt-org/cobalt.rs/pull/17#issuecomment-106625149 stated cobalt uses unstable features.

**Comment by Liamsi** [comment]
Either the docs aren't up to date or the default behaviour was changed (but I do not even get a warning abourt unstable while compiling)
I am sure that the 1.0.0 package I am using is just a vanilla rust build:
https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rust
But thanks, I think I will switch to using https://github.com/brson/multirust instead of installing the rust package via Arch's pacman.

**Comment by tak1n** [comment]
Okay I think `rust 1.0.0-dev` is pretty outdated, see for example this PR from 8 Jan 2015 https://github.com/michaelwoerister/rs-persistent-datastructures/pull/4

Rust 1.0.0 was released on 15 May
