### ISSUE TITLE
Allow users to specify posts sort order

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#160]
Something like a config flag "sort_reverse"

**Comment by bddenhartog** [comment]
I'd suggest something like the following, simply for added clarity:

```
[posts]
  sort_order = "{asc/desc}"
```

**Comment by epage** [comment]
I've been toying with both ideas without much personal preference as I've been working on my collections refactor.

**Comment by epage** [comment]
Fixed by #220
