### ISSUE TITLE
Generate binaries for simple downloading

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#164]
https://github.com/japaric/rust-everywhere/
https://github.com/japaric/xargo

**Comment by gnunicorn** [comment]
Or use [trust](https://github.com/japaric/trust) and travis to build it automatigically?

**Comment by johannhof** [comment]
I'm doing that right now, almost done. It's not as automagical as one might think, considering we have some more things we'd like to do and that we don't need most of the cross-compilation targets right now.

**Comment by johannhof** [comment]
See #176
