### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by uetoyo** [cobalt-org/cobalt.rs#167]
Unlike posts, files outside the **_posts** directory will not be indexed as blog posts and not passed to the index file in the list of contents.

Did you mean `posts` directory instead of `_posts`?

**Comment by nott** [comment]
The default value is defined in [src/config.rs#L35](https://github.com/cobalt-org/cobalt.rs/blob/090460a9aee6db2e055930e0548e21b226319a81/src/config.rs#L35) - it's `posts` indeed.

I guess `_posts` was used in earlier versions to be compatible with [jekyll](https://jekyllrb.com/docs/posts/).

@uetoyo would you like to fix this?

**Comment by uetoyo** [comment]
@nott Ok, I will fix this critical bug :)
