### ISSUE TITLE
Add the default charset to the template

### ISSUE THREAD

**Issue by uetoyo** [cobalt-org/cobalt.rs#169]
We should put the `<meta charset="utf-8">` to the default liquid template.
See the default Firefox behavior on Windows (This is a czech text with diacritics): *V přílivu žluťoučkých květů včelky se vznášejí.* 
![missing-charset](https://cloud.githubusercontent.com/assets/2691848/21046724/4eec9320-be06-11e6-90c1-4df35ca06db7.PNG)

**Comment by nott** [comment]
Thank you for the report!

If somebody wants to contribute, the template can be found here: [new.rs#L11-L30](https://github.com/cobalt-org/cobalt.rs/blob/9358b717b6ec05f12eb3a1e62f5bacd59bc38ea4/src/new.rs#L11-L30).

**Comment by uetoyo** [comment]
I will take it.

**Comment by uetoyo** [comment]
I have a failing tests on fresh copy of master branch and I am not sure if I should add some new feature.
`test result: FAILED. 5 passed; 14 failed; 0 ignored; 0 measured`

**Comment by nott** [comment]
@uteoyo could you please share these details?

* test output
* Operating System
* rust version
* cargo version

**Comment by uetoyo** [comment]
Windows 7 64bit
rustc 1.11.0 (9b21dcd6a 2016-08-15)
cargo 0.12.0-nightly (6b98d1f 2016-07-04)


```
failures:
    copy_files
    custom_paths
    custom_post_path
    custom_posts_folder
    custom_template_extensions
    dotfiles
    drafts
    drafts_not_shown_by_default
    example
    excerpts
    hidden_posts_folder
    ignore_files
    rss
    sort_posts
```

e.g 

```
failures:

---- custom_posts_folder stdout ----
        <!DOCTYPE html>
<html>
    <head>
        <title>My blog - My first Blogpost</title>
    </head>
    <body>
        <h1>My first Blogpost</h1>
<p>Hey Blogpost</h1>
<p>Hey there this is my first blogpost and this is super awesome.</p>
<p>My awesome.</p>
<p>My Blog is lorem ipsum like, yes it is..</p>

    is..</p>

    </body>
</html>


thread 'custom_posts_folder' panicked at 'assertion failed: edit distance between "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>My blog - My first Blogpost</title>\r\n    </head>\r\n    <body>\r\n        <h1>My first Blogpost</h1>\r\n<p>Hey there this is my first blogpost and this is super awesome.</p>\r\n<p>My Blog is lorem ipsum like, yes it is..</p>\r\n\r\n    </body>\r\n</html>\r\n\r\n" and "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>My blog - My first Blogpost</title>\r\n    </head>\r\n    <body>\r\n        <h1>My first Blogpost</h1>\n<p>Hey there this is my first blogpost and this is super awesome.</p>\n<p>My Blog is lorem ipsum like, yes it is..</p>\n\r\n    </body>\r\n</html>\r\n\r\n" is 6 and not 0, see diffset above', C:\Users\dlanda\.cargo\registry\src\github.com-1ecc6299db9ec823\difference-0.4.1\src\lib.rs:86
```

**Comment by nott** [comment]
trying to reproduce the issue in a win7 vm now

**Comment by nott** [comment]
@uetoyo 

Setting dev environment in my windows vm wasn't as easy as I expected. I created a PR adding meta tag: #174 

Could you please report a separate issue for the failing tests?
