### ISSUE TITLE
Markdown reference-style links are not resolved in excerpts (in most cases)

### ISSUE THREAD

**Issue by djwf** [cobalt-org/cobalt.rs#186]
In Cobalt v.0.5.0 when the excerpt is not explicitly defined in a post, any Markdown reference-style links do not resolve in excerpts unless the reference itself is immediately below or above the initial paragraph.

To be clear, the following example allows reference-style links to resolve in the first paragraph.

    title=Markdown reference-style link test
    ---
    [Markdown]: https://daringfireball.net/projects/markdown/
    Test paragraph using [Markdown][] reference-style link.

The following three examples, however, result in unresolved references.

In the first case, the excerpt ends up being completely blank.

    title=Markdown reference-style link test
    ---
    [Markdown]: https://daringfireball.net/projects/markdown/
    
    Test paragraph using [Markdown][] reference-style link.

In the second case and third case, the excerpt is displayed without the references being rendered.

    title=Markdown reference-style link test
    ---
    Test paragraph using [Markdown][] reference-style link.
    [Markdown]: https://daringfireball.net/projects/markdown/

Note that it doesn't matter if there's a line between the paragraph and reference or not, in either case references in the excerpt are not resolved.

    title=Markdown reference-style link test
    ---
    Test paragraph using [Markdown][] reference-style link.
    
    [Markdown]: https://daringfireball.net/projects/markdown/

A workaround is to move all references used in the first paragraph up to immediately precede the first paragraph, but ideally the references should work regardless of where they are placed within the file.

**Comment by nott** [comment]
Makes sense

This is how the feature is implemented in jekyll: https://github.com/jekyll/jekyll/pull/5212b
