### ISSUE TITLE
Add additional tests for additional security

### ISSUE THREAD

**Issue by uwearzt** [cobalt-org/cobalt.rs#187]
In the README there are four public repos which could be used for a more extensive "real world" test (mine will hopefully follow soon).

What I imagine:

1. build cobalt from master
2. build cobalt from a branch/pull request
3. clone the site repos
4. build the site repos with both cobalt variants
5. do a diff between the results

If that sounds like a good idea, I will go for it :)

**Comment by tak1n** [comment]
@uwearzt sounds good for me :)
