### ISSUE TITLE
Copying assets fails when source is set to "."

### ISSUE THREAD

**Issue by jmatraszek** [cobalt-org/cobalt.rs#189]
Create a new project, set source to ".", then add `style.css` or `css/style.css` -- in one case the file will be copied to `build` as `css` in other case building will fail at all.

**Comment by nott** [comment]
This might be a duplicate of #183 

There is an open PR #184 that should fix the issue. @jmatraszek could you please check whether #184 fixes your issue?

**Comment by jmatraszek** [comment]
Yes, tested it and #184 fixed this problem. Sorry for opening a duplicate! Thanks!

**Comment by nott** [comment]
Glad that helped. And thank you for testing :)
