### ISSUE TITLE
Fail to build under rustlang 1.0

### ISSUE THREAD

**Issue by shuoli84** [cobalt-org/cobalt.rs#19]
Since rust reach 1.0, should we able to build under 1.0? Now it reports 

```
this feature may not be used in the stable release channel
```

**Comment by Liamsi** [comment]
HI there, thanks for the feedback. As this project is work in progress and not ready for production use, uses some yet unstable features (path_ext, fs_walk, core and path_relative_from). 
It does not hurt to build it with a unstable version of rust (nightly). We hope that those features will stabilize soon.
To experiment with the code you could use mulitrust (or rustup). Or, if you have any suggestion on howto replace the usage of unstable features with stable ones, you are welcome to contribute :-)
