### ISSUE TITLE
Nothing copied on Windows

### ISSUE THREAD

**Issue by DenisKolodin** [cobalt-org/cobalt.rs#194]
Cobalt doesn't actually copy files (images and styles), but traces it. I have this issue on **Windows** with **MinGW/Msys2**.

```
[debug]  Layouts directory: "./src\\_layouts"
[debug]  Posts directory: "./src\\posts"
[debug]  Draft mode enabled: false
[trace]  Generating posts
[trace]  Generating posts\post-1.html
[info]   Created ./build\posts\post-1.html
[trace]  Generating other documents
[trace]  Generating index.html
[info]   Created ./build\index.html
[info]   Copying remaining assets
[debug]  Created new directory "./build\\"
[debug]  Created new directory "\\css"
[debug]  Copied "./src\\css\\style.css" to "\\css\\style.css"
[debug]  Created new directory "\\img"
[debug]  Copied "./src\\img\\browser-bottom.png" to "\\img\\browser-bottom.png"
[debug]  Copied "./src\\img\\browser-top.png" to "\\img\\browser-top.png"
[debug]  Copied "./src\\img\\screenshot.png" to "\\img\\screenshot.png"
[debug]  Created new directory "\\posts"
[info]   Build successful
```

```bash
$ cobalt -V
Cobalt 0.6.0
$ rustc -V
rustc 1.17.0-nightly (0f34b532a 2017-02-21)
```

Previous version `0.5.0` doesn't work as well.

**Comment by DenisKolodin** [comment]
Holy cow! I've found the bug: all files had copied to the root path `C:/`, because it uses `\\` prefix.

But my config is:
```yaml
name: Site
source: "./src"
dest: "./build"
ignore:
  - .git/*
  - build/*
```

**Comment by tak1n** [comment]
@DenisKolodin thx for reporting this  and looking into it a little bit. It is a little bit hard for me to debug this as I'm a non windows user.

If you can craft a pr I will happily try to merge it, other than that I will probably need to setup a vm with windows. What windows version are u using? (Hopefully I got the right one at home :smile:)

**Comment by DenisKolodin** [comment]
@tak1n No problem! I've prepared the PR.

Cobalt hadn't trimmed `"\\"` Win's separator.
Without it the path `"./src\\css\\style.css"` becomes `"\\css\\style.css"`, but not `"./build\\css\\style.css"` as expected.
