### ISSUE TITLE
Allow configuring the theme for syntax highlighting

### ISSUE THREAD

**Issue by mre** [cobalt-org/cobalt.rs#202]
Looking into a way to make the syntax highlighting theme adjustable from the config file.
For example it would be great if I could write something like this in the `.cobalt.yml`:

```yaml
theme: base16-ocean.dark
```

I have a rough prototype here: https://github.com/cobalt-org/cobalt.rs/compare/master...mre:config-theme

Unfortunately I need some more guidance for the next steps.

The part around `CodeBlock`s is not working yet.
What I wanted to do is inject the config as a parameter into the codeblock.
But the codeblock needs to implement `Renderable` from Liquid. 
(https://github.com/cobalt-org/cobalt.rs/compare/master...mre:config-theme#diff-b9237993dc7f8fb4f95923e1c2a64499R46)

The error message I get is:
```Rust
# cargo build --features="syntax-highlight"
   Compiling cobalt-bin v0.6.1 (file:///.../cobalt.rs)
error[E0281]: type mismatch: the type `fn(&str, &[liquid::Token], std::vec::Vec<liquid::lexer::Element>, &liquid::LiquidOptions, &config::Config) -> std::result::Result<Box<liquid::Renderable>, liquid::Error> {syntax_highlight::initialize_codeblock}` implements the trait `
for<'r, 'r, 'r, 'r> std::ops::Fn<(&'r str, &'r [liquid::Token], std::vec::Vec<liquid::lexer::Element>, &'r liquid::LiquidOptions, &'r config::Config)>`, but the trait `for<'r, 'r, 'r> std::ops::Fn<(&'r str, &'r [liquid::Token], std::vec::Vec<liquid::lexer::Element>, &'r li
quid::LiquidOptions)>` is required (expected a tuple with 4 elements, found one with 5 elements)
   --> src/document.rs:272:56
    |
272 |         options.blocks.insert("highlight".to_string(), Box::new(initialize_codeblock));
    |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: required for the cast to the object type `for<'r, 'r, 'r> std::ops::Fn(&'r str, &'r [liquid::Token], std::vec::Vec<liquid::lexer::Element>, &'r liquid::LiquidOptions) -> std::result::Result<Box<liquid::Renderable + 'static>, liquid::Error> + 'static`
```

That should be the last roadblock. Maybe you can give me a hint on what I could try.

**Comment by epage** [comment]
Sorry for the delay.  I'm baffled by this as well but unfortunately am on Windows so I'm a bit limited in my debugging of this situation.

**Comment by boxofrox** [comment]
FYI on the reason for the build error.

The *liquid-rust* crate defines the block `Block` type as:

```rust
// Block :: &str -> Slice Token -> Vec Element -> LiquidOptions -> Result
pub type Block = Fn(&str, &[Token], Vec<Element>, &LiquidOptions) -> Result<Box<Renderable>>;
```

@mre's changes redefine `initialize_codeblock` as:

```rust
// :: &str -> Slice Token -> Vec Element -> LiquidOptions -> Config -> Result
pub fn initialize_codeblock(_: &str, arguments: &[Token], tokens: Vec<Element>, _: &LiquidOptions, config: &Config) -> Result<Box<Renderable>, Error>
```

```diff
Block               :: &str -> Slice Token -> Vec Element -> LiquidOptions -> Result
intialize_codeblock :: &str -> Slice Token -> Vec Element -> LiquidOptions -> Config -> Result
```

The two signatures don't match and rustc is really ~~bad~~ verbose at explaining that point.

Probably the best path forward would be to switch `Block` to a trait object, so `initialize_codeblock` can have a stateful struct providing a `Config`/`Theme` to new allocations of `CodeBlock`.  tokio-service does something similar with their `NewService` trait \[[1](https://docs.rs/tokio-service/0.1.0/tokio_service/trait.NewService.html)].  But that would be an API-breaking change.

\[1]: https://docs.rs/tokio-service/0.1.0/tokio_service/trait.NewService.html
