### ISSUE TITLE
Server can't handle querystrings in CSS link

### ISSUE THREAD

**Issue by whostolemyhat** [cobalt-org/cobalt.rs#207]
I added basic [cachebusting](https://css-tricks.com/strategies-for-cache-busting-css/) to my CSS file in the `default.liquid` template:

```<link rel="stylesheet" href="/css/main.css?v=1">```

but when running `cobalt watch` or `cobalt serve` the CSS file returns a 404.

Removing the querystring `?v=1` from the CSS URL means `cobalt watch` correctly serves the file.

In addition, with the cachebusting in place, building with Cobalt then serving the static files from `/build` with another static server (in this case [http-server](https://www.npmjs.com/package/http-server)) also behaves correctly.

[Example repo](https://github.com/dontexpectanythingsensible/blog) - `_layouts/default.liquid`

**Comment by epage** [comment]
Fixed by #217
