### ISSUE TITLE
Failure on copying static file if the source folder is set to the current directory

### ISSUE THREAD

**Issue by tglman** [cobalt-org/cobalt.rs#210]
hi  All,

if you set in the .cobalt.yml
```
source: "."
```
it fail to copy the static files trimming out the file name and keeping the extension.

this can be worked around easily using instead
```
source: "./"
```

**Comment by bddenhartog** [comment]
Confirmed. A source tree like:

```text
project-name/
|- posts/
|  |- post-1.md
|
|- .cobalt.yml
|- index.liquid
|- image.png
```

Results in a build of:

```text
project-name/
|- build/
|  |- posts/
|  |  |- post-1.html
|  |
|  |- index.html
|  |- png
```

**Comment by bddenhartog** [comment]
Note that this applies to any file with an extension different from `.md` and `.liquid`.

**Comment by epage** [comment]
I'm not seeing this after #346.  I suspect its been resolved somewhere along the way.  Please let me know if this is wrong.

**Comment by tglman** [comment]
Hi,

Yes i confirm as well this is fine.

Regards
