### ISSUE TITLE
Add an extension to allow for in-template code highlighting

### ISSUE THREAD

**Issue by svenstaro** [cobalt-org/cobalt.rs#215]
Something along the lines of https://jekyllrb.com/docs/templates/#code-snippet-highlighting would be really neat to have.

**Comment by epage** [comment]
The question is: do we put this in cobalt or liquid's `extras`?

Starting tags/filters in cobalt means we can always move them to liquid later.  The main hurdle I can think of is I am unsure if liquid exposes custom tags to clients (blocks)

If this goes in liquid, we should work to minimize unwated deps for liquid's clients and make the syntax highlighter optional.

In general, we should review Jekyll's filters/tags and see which we might want and if they should go in cobalt or liquid.

**Comment by epage** [comment]
So it turns out cobalt already has this (I thought it was only for md)

See
- https://github.com/cobalt-org/cobalt.rs/blob/master/src/document.rs#L353
- #259 for customizing the theme which fixes #202 
- #200 for expanding the language support
- #180 to support more than Linux
