### ISSUE TITLE
Add support for pagination 

### ISSUE THREAD

**Issue by Svenito** [cobalt-org/cobalt.rs#219]
It'd be nice to have pagination on the index page where the post list is shown.

**Comment by epage** [comment]
Totally agree.

Without a plugin system (yet?), this seems like an area where getting it right might be hard.  We might want to start this off as an "paginatation_unstable" feature or something.

When designing this, we should consider
- Original Jekyll pagination: https://github.com/jekyll/jekyll-paginate
- Jekyll pagination fork: https://github.com/sverrirs/jekyll-paginate-v2
- Hugo's pagination: https://gohugo.io/extras/pagination/

**Comment by Svenito** [comment]
Thanks. Yes, probably not an easy addition. Also should mention that pelican provides pagination too, which might be worth considering. 
Basically it generates multiple index files for each page.
I am happy to help out somehow, but I'm still fairly new to rust.

**Comment by epage** [comment]
> I am happy to help out somehow, but I'm still fairly new to rust.

Don't let that stop you.  I got started on working on cobalt because I wanted to blog about learning Rust but wanted to use a static site generator with a better deployment story than Ruby or Python can provide.

**Comment by Svenito** [comment]
Not saying it'd stop me, just saying my rust isn't much up to scratch yet. So probably need some guidance.

I'm using cobalt for the same reason. Was on pelican, but build times are slow. Hugo needs Go runtime and Jekyll is ruby, which I also don't use generally.

Liking cobalt so far and looking forward to helping out

**Comment by bep** [comment]
>Hugo needs Go runtime

That isn't true.

I implemented Hugo's paginator if you have any questions.

**Comment by epage** [comment]
My assumption is that we'll create a special type of index page and that will have support for pagination but that we won't support any page using pagination.

So closing this in favor of https://github.com/cobalt-org/cobalt.rs/issues/354

If someone does want pagination support on any page, feel free to voice your support of re-opening this.
