### ISSUE TITLE
Cobalt should target rust stable

### ISSUE THREAD

**Issue by tak1n** [cobalt-org/cobalt.rs#22]
Remove the usage of unstable features so cobalt can be used with rust stable.

**Comment by johannhof** [comment]
I made my own fork stable some time ago to be able to run my website, you probably made some progress on this but feel free to check out my changes https://github.com/cobalt-org/cobalt.rs/compare/master...johannhof:master

**Comment by johannhof** [comment]
fixed in #24

**Comment by johannhof** [comment]
Correction: it's actually not stable right now, I'll need to do some small modifications

**Comment by tak1n** [comment]
Okay, I began to remove unstable features in https://github.com/cobalt-org/cobalt.rs/commit/029a5100616b578e89a8d03eb52ea6690186ff49

**Comment by tak1n** [comment]
Now the fun part starts: https://github.com/cobalt-org/cobalt.rs/blob/master/src/lib.rs#L1-L5
Remove the unstable features in the lib part which are used all over the place :sparkles:

**Comment by tak1n** [comment]
As of https://github.com/cobalt-org/cobalt.rs/commit/cd2c9904952645a73b600ed4e80c6e9b603b4c13 no unstable features are used.

**Comment by johannhof** [comment]
:tada:
