### ISSUE TITLE
Rendering error: Filter truncatewords not implemented

### ISSUE THREAD

**Issue by booyaa** [cobalt-org/cobalt.rs#237]
I'm getting the following build error when using travis-ci. I can't reproduce locally (on the same version of cobalt).

travis-ci versions:

- Cobalt 0.6.1
- rustc 1.18.0 (03fc9d622 2017-06-06)
- cargo 0.19.0 (28d1d60d4 2017-05-16)

cobalt build output from travis-ci (my [.travis.yml](https://github.com/booyaa/booyaa.github.io/blob/source/.travis.yml))

```
[info]   Using config file .cobalt.yml
[info]   Building from ./ into ./build
[info]   Created ./build/2017/gh-pages-custom-domain/index.html
[info]   Created ./build/2017/cobalt-github/index.html
[info]   Created ./build/2017/mba-setup/index.html
[info]   Created RSS file at ./build/rss.xml
[info]   Created ./build/about/index.html
[error]  Rendering error: Filter truncatewords not implemented
[error]  Build not successful
```
full log can be found here: https://travis-ci.org/booyaa/booyaa.github.io#L86

local versions:

- rustc 1.19.0-nightly (5b13bff52 2017-05-23)
- cargo 0.20.0-nightly (397359840 2017-05-18)
- Cobalt 0.6.1

local (Linux raspberrypi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux)

```
 $ cobalt build
[info]   Using config file .cobalt.yml
[info]   Building from ./ into ./build
[info]   Created ./build/2017/gh-pages-custom-domain/index.html
[info]   Created ./build/2017/cobalt-github/index.html
[info]   Created ./build/2017/mba-setup/index.html
[info]   Created RSS file at ./build/rss.xml
[info]   Created ./build/about/index.html
[info]   Created ./build/index.html
[info]   Created ./build/license/index.html
[info]   Copying remaining assets
[info]   Build successful
```

**Comment by epage** [comment]
Odd, `truncatewords` was added to liquid-rust towards the [end of November last year](https://github.com/cobalt-org/liquid-rust/commit/3907ae17eebefde74ee6ad58968c234101cb61fb#diff-2e72c5c98939c375bd120d0edf89270c) and liquid-rust [0.9.1 should include it](https://github.com/cobalt-org/liquid-rust/releases).

I need to do a new release of cobalt anyways, hopefully things will be less screwy then.

**Comment by booyaa** [comment]
Not sure why building cobalt v6.0.1 using trust should cause this error... 

The workaround is to install using `cargo install --git` e.g. `cargo install --git https://github.com/cobalt-org/cobalt.rs --features="syntax-highlight"`

For reference here's my original `.travis.yml` [commit](https://github.com/booyaa/booyaa.github.io/commit/f3b4149284a43dad7fe5ed9a3730d296523eeeef#diff-354f30a63fb0907d4ad57269548329e3) that was failing to build

The working version of the `.travis.yml` fiel can be found [here](https://github.com/booyaa/booyaa.github.io/commit/ba0bb28e573aeb54c4bbf038b44483cbac6480b8#diff-354f30a63fb0907d4ad57269548329e3)

**Comment by epage** [comment]
Ah, so its something we've fixed in master but haven't released yet.  Getting a release out is one of my top priorities for the project.
