### ISSUE TITLE
What is the difference between `route` and `path` in front matter?

### ISSUE THREAD

**Issue by booyaa** [cobalt-org/cobalt.rs#242]
I know with path, you can create custom paths for your blog post which can also use parameters like :day, :month?

When should I use `route` over `path`?

**Comment by epage** [comment]
Where is it you are seeing `route`?  I just looked through the code and couldn't find it.

**Comment by booyaa** [comment]
Sorry should've explained I've been looking at some of the example blogs (Johann's and Matthias'):

- https://github.com/johannhof/johannhof.github.io/blob/5b343fa983a6f0a211af4d4e5dfa0472b2174f1d/index.liquid#L4
- https://github.com/mre/mre.github.io/blob/4dcc85d67a7ae2d241619d138da12c9bcf3b482d/about/index.liquid#L3

Here's path usage (which matches up with the documentation):
- https://github.com/johannhof/johannhof.github.io/blob/b846613925a285ff4edfbe00f55fab82471ca066/license.md#title-johannhme---licensepath--license

**Comment by epage** [comment]
`route` is being used as a custom attribute

See https://github.com/johannhof/johannhof.github.io/blob/b846613925a285ff4edfbe00f55fab82471ca066/_layouts/post.liquid

My plan is to modify the front matter format to make this clearer to make it easier when copying other people's configurations.

**Comment by booyaa** [comment]
Ah ha! Thank so for clearing that up!
