### ISSUE TITLE
Can liquid template to emit http headers?

### ISSUE THREAD

**Issue by booyaa** [cobalt-org/cobalt.rs#243]
I'd like to send `Content-Type: application/json`, I tried adding it to the top of the content. 

```liquid
title: lunr index
path: /js/lunr_index.json
---
Content-Type: application.json
[
{% for post in posts %}
    { 
        "title" : "{{ post.title }}",
        "href" : "{{ post.path }}",
        "content" : "{{ post.content | strip_html | strip_newlines }}" 
    },
{% endfor %}
]
```
but this doesn't turn it into a true http header...instead it appears with the response body.

```shell
$ curl --ipv4 --silent --verbose http://localhost:3000/js/lunr_index.json
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /js/lunr_index.json HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 756
< Date: Tue, 20 Jun 2017 06:53:48 GMT
<
Content-Type: application/json
[

    {
        "title" : "Useful commit messages",
        "href" : "2017/useful-commit-messages/index.html",
        "content" : "..."
    } 
*snip*
]
```

It would be nice if you could do this via front matter.

**Comment by epage** [comment]
Thanks for pushing things in new directions!

I assume you are testing this with `cobalt serve`?  Is your interest in setting the header in just `cobalt serve` or any web server?

Is this more of a bug with `cobalt serve` correctly detecting and reporting the `Content-type`?  I think we have another issue on it for svg.

If this is a more general need, how would you go about it if you hand wrote a website?  This is an area I'm not as familiar with and would an example of what we'd need to implement would be helpful.

**Comment by epage** [comment]
Also, if this is enough of a use case, we should probably consider adding string escaping / unescaping for json like we have for HTML.

**Comment by booyaa** [comment]
Re: content type headers - apologies, I completely forgot that cobalt is a static site generator. Hosting and the source of content type of headers is handled else where in my case GitHub Pages.

I think this type of escaping is partly to create a well formatted json file, but also to allow lunr.js to successfully index the content.

I'm going to close this issue (because headers isn't something Cobalt should or need to be concerned with), but if there is a need to reference escaping JSON we can refer to this issue.

Thanks again for hearing me out.

**Comment by epage** [comment]
If interested, I've tried to make the filter writing process pretty easy.

Create a new function in [`filters.rs`](https://github.com/cobalt-org/liquid-rust/blob/master/src/filters.rs#L865), probably behind a feature flag since this isn't in base liquid and then [register it](https://github.com/cobalt-org/liquid-rust/blob/master/src/template.rs).

Prior art for dealing with json
- [Shopify's proprietary json](https://help.shopify.com/themes/liquid/filters/additional-filters#json)
- [jekyll's jsonify](https://jekyllrb.com/docs/templates/)

**Comment by booyaa** [comment]
Thanks I'll have a go!

**Comment by epage** [comment]
Oh, and the addition of serde support should help a lot!
