### ISSUE TITLE
Make frontmatter future compatible

### ISSUE THREAD

**Issue by epage** [cobalt-org/cobalt.rs#257]
Currently, the frontmatter contains
- Cobalt customization
  - With path it also then gets turned into an attribute
- Overriding of cobalt variables
- custom variables

The problem is that we could break custom variables as we add new cobalt variables or customization.

## Proposal

Frontmatter may contain:
- path
  - will be renamed to `permalink` to match Jenkins when we break compatibility on the format (from Jekyll's custom format to liquid)
  - why: for determining dest path
  - post default will change to `/:categories/:year/:month/:day/:slug.html` rather than having the same default as a page to align with Jekyll
- slug
  - why: to contribute to default dest path
- title:
  - why: rss
- description
  - why: rss
- categories
  - why: to contribute to default dest path, RSS, etc
- excerpt_separator
  - why: to determine the excerpt
- **excerpt** should we still support overriding the auto-created excerpt?
- published_date
  - renamed from `date` to make the role more clear when we added `modified_date`
  - why: rss, sorting
- format (markdown, raw, etc):
  - reinvented form of `ext`
  - why: control formatting
- layout
  - renamed from `extends` to match Jekyll
- is_draft
  - renamed from `draft` for consistency
  - why: filtering posts
- ~~is_post~~
  - Removed: Unlikely used; need to actually define semantics if we want to allow customizing this
- custom
  - why: user defined attributes

Page attributes will be
- url: absolute path
  - Renamed from `path` to clarify intent; to be like jekyll
  - See #216 for a disussion on whether it should be relative or absolute
- path: path on disk
  - Renamed from `source` to be like jekyll
- ~~slug~~
  - Removed: it was only added for Path attributes
- title
- description
- categories
- ~~excerpt_separator~~
  - Removed: it was only meant for the frontmatter to customize cobalt
- published_date
  - renamed from `date` to make the role more clear when we added `modified_date`
- ~~ext~~
  - Removed: it was meant for bookkeeping within cobalt
- ~~extends~~
  - Removed: it was only meant for the frontmatter to customize cobalt
- is_draft
  - renamed from `draft` for consistency
- is_post
- custom (eventually)
- content
- excerpt
- next
- previous

Path attributes (will be re-examined in #198)
- path: relative path of the file, without output_ext.  Normally limited to collections but I think we should make it generally available
- slug: slugified `slug` attribute, if available, otherwise file name (missing date prefix, missing extension)
- filename: raw file name (without extension).  Ideally renamed to `title` to match Jekyll when custom attributes are no longer top-level
- categories: `downcased/categeory/names`
- year
- month
- day
- hour
- minute
- second
- i_day
- i_month
- ... with `custom` attributes at top level
- ~~... with `page` attributes at top level~~
  - Removed: this was an implementation artifact

As part of this, `--dump` should add support for showing the page with all defaults filled out for ease-of-debugging.

### Jekyll

[Front matter](https://jekyllrb.com/docs/frontmatter/)
- ~~permalink~~ as path
- ~~layout~~
- ~~category / categories~~
- tags
  - why: feature not implemented yet
- ~~date~~
- ~~published (bool)~~ as is_draft

Anything else is considered a custom variable and is passed along to liquid without any scoping to protect against breaking compatibility

[Page attributes](https://jekyllrb.com/docs/variables/)
- ~~url~~
- ~~path~~
- ~~title~~
- ~~id~~
  - why: we have our own identifier for RSS
- ~~categories~~
- tags
  - why: feature not implemented yet
- ~~date~~ as published_date
- ~~content~~
- ~~excerpt~~
- ~~next~~
- ~~previous~~

[Path attributes](https://jekyllrb.com/docs/permalinks/)

### Hugo

[Front matter](https://gohugo.io/content/front-matter/)
- ~~title~~
- ~~description~~
- ~~date~~
- taxonomies (like categories and tags?)
- aliases (for moving pages)
- ~~draft (bool)~~
- ~~publishdate~~
- expirydate
- type
- CJKLanguage
- weight (sorting)
- ~~markup (rst or md)~~ as format
- ~~slug~~
- ~~url~~ as permalink

Anything else is considered a custom variable and is passed along to liquid under `.Params`.

[Page attributes](https://gohugo.io/templates/variables/)

### gutenburg

[Front matter](https://github.com/Keats/gutenberg)
- title
- description
- date: a YYYY-MM-DD or RFC339 formatted date
- slug: what slug to use in the url
- url: this overrides the slug and make this page accessible at {config.base_url}/{url}
- tags: an array of strings
- category: only one category is allowed
- draft: whether the post is a draft or not
- template: if you want to change the template used to render that specific page
- aliases: which URL to redirect to the new: useful when you changed a page URL and don't want to 404
- extra (custom)

**Comment by boxofrox** [comment]
> gutenburg
> - date: a YYYY-MM-DD or RFC339 formatted date

Is this to say support for RFC339 dates is planned?  If so, looking forward to this.

**Comment by epage** [comment]
That was a comparison with other static site generators to see how my proposal compares.

Is there a reason you'd like RFC339 over the current format?

**Comment by boxofrox** [comment]
> Is there a reason you'd like RFC339 over the current format?

No convincing reason, really.  As a practice, I use `YYYY-MM-DD` dates to organize filenames and directories and I'm fond of typing my dates that way.  The `DD MMM YYYY ...` format is a bit foreign, but nothing I can't get used to.

**Comment by epage** [comment]
Understandable.

**Comment by epage** [comment]
Status: the internal representation of the frontmatter has been updated to the new format.  We still load using the old format but then convert it to the new format.

See #262
