### ISSUE TITLE
Trailing path component treated as a directory when generating file names but as a filename when generating `path` variable

### ISSUE THREAD

**Issue by wezm** [cobalt-org/cobalt.rs#297]
I set `post_path` in `.cobalt.yml` to `post/:slug`, which generates posts as I expect. However when I use `path` in my post layout the path does not match the format specified by `post_path`:

E.g. `cobalt build` output:

[info]   Created public/post/finding-an-alternative-to-mac-os-x-part-2/index.html

`_layouts/post.liquid`:

```liquid
<h1><a href="{{ path }}">{{ title }}</a></h1>
```
Generated markup:

```html
<h1><a href="posts/finding-an-alternative-to-mac-os-x-part-2.html">Finding an Alternative to Mac OS X — Part 2</a></h1>
```

I'm expecting that `{{ path }}` would use the format specified by `post_path` so that the link works. I.e.

```html
<h1><a href="post/finding-an-alternative-to-mac-os-x-part-2/">Finding an Alternative to Mac OS X — Part 2</a></h1>
```

**Workaround**: add a trailing `/` to `post_path`

**Comment by wezm** [comment]
Hmm adding a trailing `/`/ to `post_path` seems to help.

**Comment by epage** [comment]
If its not, this should be documented.

If there is a recommendation for a better way for us to detect when `index.html` is meant to be appended, it'd be appreciated.

**Comment by epage** [comment]
Drat, I wrote that based on the update but forgot the original issue: that it was treated inconsistently.

**Comment by epage** [comment]
What version of cobalt did you see this with?

**Comment by wezm** [comment]
0.7.3

**Comment by epage** [comment]
Strange, https://github.com/cobalt-org/cobalt.rs/commit/7f571a8bd5b75adcdfc5de103778a210bbc2f5e3 is where I simplified this code and I can't see how to get into this situation.  In addition, I've been testing (not using layouts and only with a `path` inside frontmatter) and I've not reproduced this.  Seems like I need to experiment with getting closer to your setup.

**Comment by epage** [comment]
Did not reproduce with `post_path` in the global config.  Now trying a layout

**Comment by wezm** [comment]
I can't do it right now but I can try reproducing at home tonight to see if there's any more info I can get you.

**Comment by epage** [comment]
So I've gotten as close as I can think of to your scenario and cannot reproduce.  Maybe a sample git repo?

**Comment by wezm** [comment]
So I tried this again on both the computers I was using to work on my site and have been unable to reproduce it. It's really strange. I copied the code in the top post straight from what I was seeing in the browser. Thanks so much for looking into it and sorry for wasting your time.
