### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by tak1n** [cobalt-org/cobalt.rs#3]
Learn testing with rust and add:

- [ ] Unit tests
- [ ] Integration tests

**Comment by Liamsi** [comment]
Additionally, we could test the code using a fuzzer: https://github.com/kmcallister/afl.rs/blob/master/README.md
The LLVM project uses a build-bot which runs tests with the fuzzer continuously:
http://blog.llvm.org/2015/04/fuzz-all-clangs.html

**Comment by johannhof** [comment]
The test setup should be good for now.
