### ISSUE TITLE
CI fails when building a tag

### ISSUE THREAD

**Issue by epage** [cobalt-org/cobalt.rs#305]
Note: The binaries seem to still get uploaded.  This is mostly superficial (except for the scare on each release).

When pushing a tag, the CI will build binaries and upload them to github.  It does this for every target that builds `stable`.

We have a job dedicated to building rustfmt on stable.  This then fails.  See [example](https://travis-ci.org/cobalt-org/cobalt.rs/builds/290721243).

Requirements
- Should not start passing because it uploads a binary to github (that target is already handled)
- Should not start passing because we just moved rustfmt-nightly.  New rustfmt will be running on stable again soon.  If we want to move rustfmt on nightly just to avoid this, it should be recognized as such.

Options
- Add to the deploy condition
- Move rustfmt into the regular stable jobs
- Always run rustfmt on nightly even if it isn't needed

**Comment by Geobert** [comment]
I did not understand the issue here (came here because you pointed this in the PR)

**Comment by epage** [comment]
Whenever I roll out a new release (like 0.11.1), I tag the release using git.  This is what triggers the CI to deploy a binary to the [github releases page](https://github.com/cobalt-org/cobalt.rs/releases).

The problem is the `deploy` happens for every job that runs on "stable".  `rustfmt` runs on stable but is not meant to be deployed, causing a build error.  This is annoying because I get a build error and have to go check it to make sure something more catastrophic didn't fail.

[example](https://travis-ci.org/cobalt-org/cobalt.rs/jobs/327075801)

I think I linked to this when brainstorming an idea to speed up our builds.  I brought this up as a caution for how things can go wrong when splitting one job into two.
