### ISSUE TITLE
Chokes on vim swap files

### ISSUE THREAD

**Issue by durka** [cobalt-org/cobalt.rs#31]
If I don't delete *.swp before running `cobalt build`, it sometimes dies saying there is invalid UTF-8 in a file. Probably, it should either skip non-UTF-8 files (and emit a warning), or know how to skip common editor swap files.

**Comment by johannhof** [comment]
Hi there, thanks for reporting!

I would actually say we need both functionalities. It shouldn't crash on invalid UTF-8 but maybe just skip the file with a warning. (We'd have to ramp up the error handling system for that).

We should also provide an --ignore flag (which could also be a .cobalt.yml option later) that could be passed a list of file endings to not copy.

I would recommend doing the latter option first. It shouldn't be too hard. If you want to give it a shot, I'd be happy to support you.

**Comment by durka** [comment]
See my other PR for a small ramp-up of the error handling system :)

**Comment by durka** [comment]
Hmm, I see it already skips dotfiles, so vim's `.post.md.swp` shouldn't be a problem... now I need to figure out which files it was crashing on before. It _was_ fixed by deleting `*.swp` so there is something strange going on.

**Comment by durka** [comment]
Aha, it doesn't skip dotfiles in the layout directory! That's the bug, I think.

**Comment by durka** [comment]
See new PR.
