### ISSUE TITLE
Create conversion utility to simplify migration

### ISSUE THREAD

**Issue by epage** [cobalt-org/cobalt.rs#334]
Conversions
- [x] Config file (#199)
- [x] Include paths (#328)
- [x] Frontmatter (#257)
- [x] Permalink (#198)
- [ ] `posts` variable (#323)
- [x] Rename config file (#348)

Test cases
- [tak1n.github.io](https://tak1n.github.io) [Source](https://github.com/tak1n/tak1n.github.io)
- [johannh.me](http://johannh.me) [Source](https://github.com/johannhof/johannhof.github.io)
- [kstep.me](http://kstep.me) [Source](https://github.com/kstep/kstep.github.com)
- [matthias-endler.de](https://matthias-endler.de/) [Source](https://github.com/mre/mre.github.io)
- [sda.io](https://sda.io) [Source](https://github.com/mfs/blog)
- [booyaa.wtf](https://booyaa.wtf/tags/cobalt/) [Source](https://github.com/booyaa/booyaa.github.io)
- [uwe-arzt.de](https://uwe-arzt.de) [Source](https://github.com/uwearzt/site-uwe-arzt.git)

**Comment by badboy** [comment]
- http://fnordig.de/ / https://github.com/badboy/fnordig.de
- https://github.com/badboy/hellorust (not yet officially published)

**Comment by mnivoliez** [comment]
Hello!
I though I should put here that I use cobalt to.
[Sources](https://gitlab.deep-nope.me/mnivoliez/deep-blog)
[Site](https://blog.deep-nope.me/)

**Comment by epage** [comment]
Great to see someone running gitlab!  Feel free to give us feedback on the CI file in our docs.

**Comment by epage** [comment]
Fixed by https://github.com/cobalt-org/cobalt.rs/pull/346
