### ISSUE TITLE
Source directory parameter

### ISSUE THREAD

**Issue by rrees** [cobalt-org/cobalt.rs#336]
It looks as though the `watch` and `build` command no longer take a `source` parameter. I'm assume that the configuration YAML file is the only way to configure this now.

However the README still has a reference to the `-s` parameter.

I tried to look over the PRs to see whether this is a case of the documentation being out of date but I couldn't find anything clear on the matter and thought I'd raise the issue instead to hopefully clarify the situation.

**Comment by epage** [comment]
Sorry for the confusion; cobalt is in a state of transition.

I'm waiting until I finish the major transitions (see [0.10.0 milestone](https://github.com/cobalt-org/cobalt.rs/milestone/7)) before I revamp the documentation (see #73 and #78).

If you're curious,  more information on why `--source` was removed can be found in the [commit](https://github.com/cobalt-org/cobalt.rs/pull/308/commits/70b549dac31e444095768166bea37ab0f9f108a1) and PR #308.

Was this just an FYI of a discrepancy you noticed or were you interested in using the flag?  If you were interested in using it, I'd be curious to know more about your use case to make sure I'm designing out important workflows.

**Comment by epage** [comment]
Sorry for the confusion; cobalt is in a state of transition.

I'm waiting until I finish the major transitions (see [0.10.0 milestone](https://github.com/cobalt-org/cobalt.rs/milestone/7)) before I revamp the documentation (see #73 and #78).

If you're curious,  more information on why `--source` was removed can be found in the [commit](https://github.com/cobalt-org/cobalt.rs/pull/308/commits/70b549dac31e444095768166bea37ab0f9f108a1) and PR #308.

Was this just an FYI of a discrepancy you noticed or were you interested in using the flag?  If you were interested in using it, I'd be curious to know more about your use case to make sure I'm designing out important workflows.

**Comment by rrees** [comment]
I had a makefile that used the flag rather than having a config file. So when I upgraded my build script broke.

I added a config file to fix it but then started to look into why the flag had been removed.

I understand the reasoning behind standardising on the config file but for me I was effectively using the build script as the configuration rather than having it in two places.

**Comment by epage** [comment]
What else is your makefile doing out of curiosity?  I'm wondering if its a lack of functionality :)

> I understand the reasoning behind standardising on the config file but for me I was effectively using the build script as the configuration rather than having it in two places.

The question is whether a no-config scenario would be common enough to support or is this more of a one-off case.

Improved defaults (which my 0.10 milestone is changing defaults) might also help.  Do you mind sharing your config?

**Comment by epage** [comment]
Also, if your site is public, could you post the link on #334?  I'm tracking test cases for the conversion tool to help minimize the pain of breaking format compatibility.

**Comment by rrees** [comment]
My site isn't public yet unfortunately.

My Makefile basically this:

```
build:
	cobalt build --destination _build

deploy: build
	netlify deploy --site-id my_site_id --path _build

serve:
	cobalt watch --drafts --port 6767 --destination _build
```

Essentially it's just encapsulating my workflow so that I don't have to remember the parameters.

Having just put it in, I've noticed a slightly issue as I'm sharing my development build folder and my deployment one. Whoops!

**Comment by epage** [comment]
> My site isn't public yet unfortunately.

Don't worry, I suspect the transition will be smooth with migration subcommand.

> Essentially it's just encapsulating my workflow so that I don't have to remember the parameters.

Handy.

Would cobalt and netlify's config files get you most of the way to having the workflow saved off?
- `--port 6767`: Is there a reason you go with a custom port?  Jekyll keeps the port in the config file.  Should I offer that?
- `--destination`: Cobalt now exposes `base_url` to more than RSS so paths can work correctly.  My thought was to have `serve`/`watch` override the `base_url` so the site would still work.  I wonder if we should also override `destination` to a temp directory since what is being generated isn't the "true" site.
- `--drafts`: With just this left, it makes me start to question if we should also change the default for this for `serve`/`watch`

Thoughts?

**Comment by epage** [comment]
Before jumping on making these changes, something else I want to consider is a matter of workflows. 

For the other hosts, we rely on a CI deploying the site on commit.  My initial reaction is to encourage this type of workflow because it has some good practices in it (automated pipeline vs manual, checked into VCS, etc).  From my quick look on netlify's site, it seemed to have some kind of CI support.

Is there a reason you aren't using netlify's CI?

**Comment by rrees** [comment]
@epage the Netlify CI is a bit complex for me but also it doesn't support Rust either

I use custom port rules because I tend to be working on different sites at the same time (mostly Jekyll sites) so yes I could embed the port into the configuration no problem as it's not really dynamic.

Having a default "temp" build folder for `serve/watch` makes sense to me. I'm not sure whether drafts should be the default setting though as I feel the defaults should be generally be "production ready".

**Comment by epage** [comment]
> My thought was to have serve/watch override the base_url so the site would still work. I wonder if we should also override destination to a temp directory since what is being generated isn't the "true" site.

In #397, I'm switching `cobalt import` to do a `cobalt clean` / `cobalt build` first.  This is an alternative way of addressing this problem, for those using `cobalt import`.  In this case, `cobalt build` is being done.  It'd probably be more appropriate for the makefile to do a clean before the build.

If that is done, it saves from the extra complexity and documentation associated with making the `destination` dynamic.

With that, I'm somewhat leaning towards not doing this extra stuff and just having people with more interesting workflows to use something like make.  Maybe in the long run, we'll eventually get to this but unless someone is pushing for it, probably not for a bit.  I think I'll go ahead and close this.
