### ISSUE TITLE
Static files with custom paths

### ISSUE THREAD

**Issue by tkornack** [cobalt-org/cobalt.rs#338]
Let's say you have a post in a subdirectory, posts/post_dir/ with some static files/images. This builds:

- The page at the custom path: /custom-post-path/index.html
- The images at the posts path, like /posts/post_dir/image.jpg

Is there a way to obtain reference where those images wind up so that I don't have to hard code the path? "/posts/{{source}}" almost works, but I only want the path, without the page file. I could use something like "/posts/{{source_path}}"? Otherwise I have to hard code the paths to the static files. Copying the images to the custom path, I imagine, is a non-starter because they might be referenced by more than one pages.

**Comment by epage** [comment]
So let me see if I understand.

You keep your post and its assets in a folder but are using a custom path for the post.  This means you can't just use a relative path to the assets because they end up in a different location.  So you'd like some way of knowing where they end up.

One solution would be to expose a variable to your post that is the path it would exist in if you didn't use a custom path.  The hard thing will be to come up with a meaningful name for this.  Suggestions?

**Comment by epage** [comment]
Also, to talk real quick on workflows.

I assumed people would take one of two approaches
- Standard-path posts with assets next to them (same location in source and dest)
- Custom-path posts with assets in a dedicated folder (different locations in source and dest)

What you seem to be doing is a hybrid
- Assets and posts in the same location in the source but different locations in the dest.

Could you help me understand why you chose this workflow?  

Why is this helpful?
- I might document workflows as part of #73 and understanding what people want to do and why is helpful
- Help in naming the variable if we go that route.
- We might decide this is an obscure enough workflow that it would detract from the UX for everyone else to build-in support for this.

**Comment by tkornack** [comment]
Hi! Thanks for the reply. For context, the site is [Twinleaf](http://www.twinleaf.com). We're using custom-path posts for products. It would just be handy to have the assets in the same folder as the post in this case: keeps the thing photos with the thing page.

Honestly I was just looking for a handy templating system and just bent cobalt posts to our needs. 
You can see that we could build a fully static directory tree with templates applied to the pages in that structure.

**Comment by epage** [comment]
Cool!

> Honestly I was just looking for a handy templating system and just bent cobalt posts to our needs.

Down the road, I plan to generalize support for "posts" so you can have custom defined "collections" so it'll seem like less of an abuse of cobalt :)

>  It would just be handy to have the assets in the same folder as the post in this case: keeps the thing photos with the thing page.

And I think that can be neat.  The hard part is coming up with how to configure this so it makes sense.

**Comment by tkornack** [comment]
Having a {{source_dir}} that I could place before each image link would work for now. Same as {{source}} without the file name.

**Comment by epage** [comment]
I think doing that minimal level is reasonable.

btw I was considering getting rid of `{{source}}` because I can't see why it'd be useful yo anyone.

**Comment by tkornack** [comment]
Agreed on the uselessness of {{source}}.

**Comment by epage** [comment]
The reason for `{{source_dir}}` is to access content without a custom path.  We've discussed `source` to communicate this.  Another option is `assets`

Currently document's have `path` for their URL (mostly useful from other documents accessing the `posts` variable), so for consistency `path` might be better than `dir`.

So another option `{{assets_path}}`.

When implementing features, I like to also consider prior art
- Jekyll
  - `page.url`: path to rendered page
  - `page.path` path to unrendered page
- Hugo
  - `.Permalink`: path to rendered page (I think)
  - `.RelPermalink`: relative path to rendered page (I think)
  - `.URL`: URL for page relative to webroot (how is this different than `.Permalink`?)
  - `.Dir`: directory of unrendered page (I think)
  - `.File.Path`: path to unrendered page
  - `.File.Dir`: documentation for this is confusing

I feel like Hugo's `File` makes it nice and explicit.

(sorry if it feels I'm over thinking this;; I'm trying to plan features ahead of time to avoid changing them and disrupting people.  I've already got one major disruption planned, I'd rather not have more).

> Agreed on the uselessness of {{source}}.

Found the reason for it:
>  The path to the raw post or page. Example usage: Linking back to the         page or post’s source on GitHub

https://jekyllrb.com/docs/variables/#page-variables

**Comment by tkornack** [comment]
Perfect. Thanks.
