### ISSUE TITLE
Is it possible to disable syntax highlighting in config?

### ISSUE THREAD

**Issue by freiguy1** [cobalt-org/cobalt.rs#343]
Here's my use case. I'm using gitlab ci with the recommended cobalt container. It has syntax-highlighting feature turned on, but I was doing all the highlighting myself using highlight.js.  I want to keep using the same CI, but I don't want cobalt's default syntax highlighting.

Thanks!

**Comment by epage** [comment]
Currently, it can only be disabled at build time but I think its reasonable to also add a config flag for it.

Is there a specific format that the code block needs to be in for highlight.js?

**Comment by freiguy1** [comment]
Thanks for the quick response! So I'm not too familiar with how it all works, but I'll do my best to describe.

Without code highlighting enabled @ build time, here's what my markdown looks like (without that last backslash, idk how to escape markdown in markdown):

```text
```html
<div class="container">
    <p>Hello World</p>
</div>
\```
```

After cobalt builds, this is what the html looks like:

```html
<pre><code class="language-html">&lt;div class=&quot;container&quot;&gt;
    &lt;p&gt;Hello World&lt;/p&gt;
&lt;/div&gt;
</code></pre>
```

This html is much different than what cobalt produces with syntax highlighting enabled (which is expected). Now the key to highlight.js is that at the end of my page, I have these lines:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/highlight.min.js"></script>
<script type="text/javascript">hljs.initHighlightingOnLoad();</script>
```

When `hljs.initHighlightOnLoad()` is ran, that's when the html inside `<pre><code> elements gets modified. I guess what I like about hljs is the flexibility to add any language - even obscure ones. Maybe you can do that with cobalt's built in highlighting, but.. I'm lazy and since I had it working with hljs, I just wanted it to keep working :)

**Comment by epage** [comment]
So cobalt's current output is good enough?  Thats helpful to know.

**Comment by freiguy1** [comment]
Yes! Cobalt's current output is perfect for hljs.
