### ISSUE TITLE
Should cobalt use the native yml date/time format

### ISSUE THREAD

**Issue by epage** [cobalt-org/cobalt.rs#349]
See the [spec](http://yaml.org/type/timestamp.html).

It looks like Jekyll advertises [a specific flavor](https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts).

**Comment by epage** [comment]
While frontmatter is yml.,
- `_data` can also be toml ([similar](https://github.com/toml-lang/toml#user-content-offset-date-time) but probably not same as yml) or json (no time format)
- We also need to consider what format is "native" to liquid.

**Comment by epage** [comment]
RE Liquid

The main use case I find is the `date` filter
- [`date` filter](https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L244) calls
- [`Utils.to_date`](https://github.com/Shopify/liquid/blob/master/lib/liquid/utils.rb#L63)
  - If already a date time, no need to parse
  - If looks like an integer, [parse as timestamp](https://ruby-doc.org/core-2.2.0/Time.html#method-c-at)
  - If looks like a string, `downcase` and use [`Time.parse`](https://svn.ruby-lang.org/cgi-bin/viewvc.cgi/trunk/lib/time.rb?revision=60216&view=markup#l312) which is implemented by [`date__parse`](https://github.com/racker/ruby-1.9.3-lucid/blob/cdb0ad5299aaae6ca14d669738d65bf85691bfef/ext/date/date_parse.c#L1520) ([upstream without syntax highlighting](https://svn.ruby-lang.org/cgi-bin/viewvc.cgi/trunk/ext/date/date_parse.c?revision=56317&view=markup#l2049)).
    - This supports a *lot* of different formats, subsets, etc.

**Comment by epage** [comment]
The commit that cobalt's format was introduced in doesn't provide much reasoning

https://github.com/cobalt-org/cobalt.rs/commit/8bd07225a67d74571c7e0870a3b0bd30e56f2d74

**Comment by epage** [comment]
So summary of my thoughts
- Use a format that is cross-format (ie not yml specific)
- We should make the time portion optional, like [Jekyll](https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts)
- Main contenders would be the current format (28 December 2017 15:45:10 +0800) or [Jekyll's](https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts) (2017-12-28 15:45:10 +0800).

**Comment by epage** [comment]
```ruby
irb(main):003:0> Time.parse("05 December 2017 15:23:00 +0800")
=> 2017-12-05 15:23:00 +0800
```

Looks like `Time.parse` supports our format, therefore the `date` filter should support it, therefore we know it doesn't conflict with other potential date formats to parse in Ruby's complex parse function, therefore the existing format is future compatible.

**Comment by Geobert** [comment]
Let's support them all? give some flexibility to the user. 

If optional, when sorting by order, do we put them at the beginning or the end (atm, we fallback to beginning of time) 

I like the Jekyll's format best, I don't like having the month fully written ^^'

**Comment by epage** [comment]
The `date` filter should support a variety of inputs because the source of the data can be a lot of different things (and because the official version of liquid does it).

I don't see much value in supporting multiple formats in the frontmatter.  This is data written by the user specifically for cobalt.  We'd need to document the choices which adds noise to the documentation.  I've been working to make cobalt opinionated in things that people should have no reason to change (like names of the `_` prefixed directories) while keeping it flexible for a lot of other things.

**Comment by Geobert** [comment]
I see, I didn't think of the documentation aspect, you're totally right :)
