### ISSUE TITLE
Add an option to set filetypes/directories to ignore

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#36]
See #31, this would be actually be quite easy to implement.

We need to

- add an additional option flag in main.rs
- pass that to cobalt::build
- in cobalt::build extend the walkdir filter with a check for the filename

**Comment by achernyak** [comment]
I can take this on. Should have a working solution in the next couple days.

**Comment by LucioFranco** [comment]
@achernyak have you made any progress? 😄

**Comment by achernyak** [comment]
@LucioFranco working through it now. Apologize for the delay, work got really crazy out of nowhere.

I will have a pr submitted this week.

**Comment by johannhof** [comment]
Closed by #96
