### ISSUE TITLE
Actix-web website now made with cobalt-rs, and make a actix-website-template for us.

### ISSUE THREAD

**Issue by krircc** [cobalt-org/cobalt.rs#360]
[Actix-web website](https://actix.github.io/)
[actix-website-template](https://github.com/actix/actix-website)
I want to say thank you very much!

**Comment by epage** [comment]
Awesome!

Seems like you'll appreviate #301 which will make theming easier.

I'm having a hard time deciphering your website build process.  Your ghp's repo doesn't have a branch for your site source.  What is your process for your site?

**Comment by krircc** [comment]
@epage oh sorry .  It's a website template use cobalt.  
the  site source : [actix.github.io](https://github.com/actix/actix.github.io)

**Comment by epage** [comment]
Your `*.github.io` repo seems to only contain the built HTML (`master` branch).  I'm not seeing a `source` branch with the cobalt files its being built from.
- Is that posted somewhere?
- What workflow are you using for deployment?  Is there a reason you aren't building from the `source` branch to `master` with travis?

To clarify, my questions are so
- I can understand use cases
- Things aren't lost in the documentation
- Possibly link your site as one of the examples

**Comment by krircc** [comment]
It's my wrong. let me explain it. 
1- I make the [actix-website-template](https://github.com/actix/actix-website), then 'cobalt watch' get website source in build DIR.
2- copy the file in build DIR to [actix.github.io](https://github.com/actix/actix.github.io), so the new 
[Actix-web website](https://actix.github.io/) comming.
 I want to say thank you. and I'm very happy to make more buautiful themes for cobalt when [#301](https://github.com/cobalt-org/cobalt.rs/issues/301) be done.
