### ISSUE TITLE
Make extensions optional in frontmatter's `layout: blah.liquid` field

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/cobalt.rs#376]
At the moment, `.liquid` extension is mandatory. 

Is there any reason for this?

Again, converting from Jekyll where the layout are often `.html` and no extensions are specified in the front make the converted post failing.

Suggestion for the Liquid error message:
`Caused by: Layout post can not be read (defined in "posts/2017-05-03-scary-pockets.html"): The system cannot find the file specified. (os error 2)`

add quotes around the name of the layout:
`Caused by: Layout "post" can not be read (defined in "posts/2017-05-03-scary-pockets.html"): The system cannot find the file specified. (os error 2)`

It took me a while to spot the error here ^^'

**Comment by epage** [comment]
This looks like two separate issues
- Required extension:
  - Besides conversion, what value do we gain by this?  
  - Could we add extensions in the converter?
- Error improvements: this seems reasonable

**Comment by Geobert** [comment]
I'll ask the question the other way: why extension is mandatory?
Even outside the conversion scenario, using cobalt and having to type .liquid for all layouts field seems useless. Or am I missing something?

**Comment by epage** [comment]
- What would be the desired behavior?  Do we create a hard coded list of supported extensions and try them all?  Do we use `template_extensions`?  Do we just enumerate the directory, dropping extensions from every file?
- Maybe its just me but there is a certain level of appeal to explicitness
- Not having to do all of that is easier to document, validate, and avoids yet another performance papercut.

**Comment by Geobert** [comment]
> Not having to do all of that is easier to document, validate, and avoids yet another performance papercut.

hm fair enough :) 

Let's add extension into the converter then, but I need to make my though clear on the subject, because Jekyll's theme uses `.html` as extension. I'll do this when I'll tackle the theme conversion subject

**Comment by epage** [comment]
With #388, we are no eagerly loading all layouts.  One way to improve the error messages is to use an ngram crate to find typos.

**Comment by epage** [comment]
For errors, I created https://github.com/cobalt-org/liquid-rust/issues/184

For migration, I created https://github.com/cobalt-org/cobalt-migrate-jekyll/issues/1
