### ISSUE TITLE
Unable to build project -> "failed to run custom build command for `onig_sys v65.0.1`"

### ISSUE THREAD

**Issue by Bluesir9** [cobalt-org/cobalt.rs#380]
Rust newbie here. 

I was trying to build the project using "cargo build --release" and this error was thrown:

```
failed to run custom build command for `onig_sys v65.0.1`
process didn't exit successfully: `/home/bluesir9/Documents/open-source-contribute-projects/cobalt-repo/cobalt.rs/target/release/build/onig_sys-a3c5599ed3218922/build-script-build` (exit code: 101)
--- stdout
running: "/opt/cmake-3.10.2/bin" "/home/bluesir9/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-65.0.1/oniguruma" "-DBUILD_SHARED_LIBS=OFF" "-DCMAKE_INSTALL_PREFIX=/home/bluesir9/Documents/open-source-contribute-projects/cobalt-repo/cobalt.rs/target/release/build/onig_sys-c6f4579e58b0aa90/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"

--- stderr
thread 'main' panicked at '
failed to execute command: Permission denied (os error 13)

build script failed, must exit now', /home/bluesir9/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.29/src/lib.rs:632:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Earlier when I had run the same command it would throw an error saying something along the lines of cmake is not installed, so I installed it separately and now I am stuck on this issue.

**Comment by uwearzt** [comment]
Hi bluesir9,

1. on which distribution?
2. How did you install cmake?

This Looks like a permission related problem.

**Comment by Bluesir9** [comment]
Ubuntu 16.04 LTS

I downloaded the tar from their page, extracted it into the /opt the directory, ran the necessary commands as instructed [here](https://cmake.org/install/) and then added its bin folder to the path.

**Comment by uwearzt** [comment]
Ah ok, on Ubuntu you should use the provided cmake, install with
```sudo apt install cmake```.  I guess no one has tried with the latest cmake.

Maybe this already fixes the problem, if not i would try to change the permissions on the ```.cargo```directory: ```sudo chown -R bluesir9:bluesir9 ~/.cargo``` to take the ownership of the complete ```.cargo```directory.

**Comment by epage** [comment]
While we'd appreciate you being able to work with us to resolve the problem so we can improve the docs, you can get away with building cobalt with `--no-default-features` which will disable support for syntax highlighting which is what needs this lib.

**Comment by Bluesir9** [comment]
@uwearzt installing cmake using apt did the trick. Maybe this could be added to the docs as part of the installation steps. 

That said, I will close this issue now.
