### ISSUE TITLE
"cobalt new --destination posts" does not seem to work

### ISSUE THREAD

**Issue by haheute** [cobalt-org/cobalt.rs#390]
Hello. 

I am new to cobalt and use 0.11.1 installed with `cargo install cobalt-bin`.
This command from the [docs](http://cobalt-org.github.io/docs/usage.html) does not create a 'post' in the `posts` directory, but a page in the current folder (project root):
`cobalt new "Cats Around the World" --destination posts`

I have to do `cobalt new "My new post"` inside the posts directory, then it works.

**Comment by epage** [comment]
Looks like this is a bug in the docs.  Its supposed to be `--file`.

**Comment by epage** [comment]
It is ... unfortunate that `--destination` is available on commands that don't need it, like `new`.  That can be a separate thing though

Fixed this with https://github.com/cobalt-org/cobalt-org.github.io/commit/b069f461b2042b15763710ba63cb42da1bcb0f44
