### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by tak1n** [cobalt-org/cobalt.rs#4]
After #3 is resolved and proper testing was added refactor "bad" code out.

**Comment by tak1n** [comment]
Removing the usage of unstable features introduced some weird complexity (mostly because I don't know rust that good yet).

See https://github.com/cobalt-org/cobalt.rs/commit/cd2c9904952645a73b600ed4e80c6e9b603b4c13 and https://github.com/cobalt-org/cobalt.rs/commit/30e08c84dd81be62d5aed54319568f0ecb070362

**Comment by johannhof** [comment]
62ce74bad07169de9d1f155bbcfa27c8cdea5a69 and 7b63603e5b4b3e65c02ebfbcd12cdc00961c06b3 should do it
