### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [cobalt-org/cobalt.rs#40]
Reply to this issue with what license you'd like, and I'll attempt to contact everyone on  https://github.com/cobalt-org/cobalt.rs/graphs/contributors to make sure they're ok with it, then PR the license files and cargo.toml license line.

**Comment by johannhof** [comment]
@cobalt-org/owners MIT?

**Comment by johannhof** [comment]
wow did we not do that yet

**Comment by tak1n** [comment]
I'm fine with that :)

**Comment by edunham** [comment]
Fortunately the contributors list is still short (checking these off as people ack MIT; feel free to edit this comment):
- [x] @tak1n 
- [x] @johannhof 
- [ ] @Liamsi 
- [ ] @nathanross 
- [ ] @skade 
- [ ] @durka

**Comment by durka** [comment]
ACK

**Comment by nathanross** [comment]
200 OK

**Comment by johannhof** [comment]
Closed by #42
