### ISSUE TITLE
Support jekyll-style frontmatter in the content

### ISSUE THREAD

**Issue by berkus** [cobalt-org/cobalt.rs#431]
I don't know why decision was made to not follow the jekyll frontmatter syntax, but some editors, notably Sublime Text include highlighting schemes that rely on it, compare:

1. Cobalt front matter
![one-separator-st3](https://user-images.githubusercontent.com/80306/39259459-20acd7aa-48bf-11e8-9fc7-0f05eb8c3fed.png)

2. Jekyll front matter
![two-separators-st3](https://user-images.githubusercontent.com/80306/39259466-255a14de-48bf-11e8-9900-fa3c9079af41.png)

And I believe some other markdown editors might be doing the same - e.g. github is able to extract jekyll front matter in a .md page and show it in tabular form, see for example [here](https://github.com/metta-systems/metta.systems/blob/80a0f5a42e966eba95e22277bf69b026a2fa0627/content/post/2012-07-16-graphic-dependency-resolution.md) while with cobalt front matter things look [much much worse by default](https://github.com/cobalt-org/cobalt-org.github.io/blob/source/help.md).

**Comment by epage** [comment]
I think we could implement this by checking for `"^---\n.*---\n"` in addition to just `"---\n"`.

The code is here
https://github.com/cobalt-org/cobalt.rs/blob/master/src/cobalt_model/document.rs#L46

We could look to the jekyll import for inspiration
https://github.com/cobalt-org/cobalt.rs/blob/master/src/jekyll_model/document.rs#L49

**Comment by freiguy1** [comment]
Would this be a requirement for documents or optional? In other words, if both triple-dashes were required, in this example:

```
title: The Title
---
The content
```

There would be no frontmatter since there's only one triple-dash?

I have a feeling implementing both triple-dashes as a requirement would be easier however, it's a breaking change for anyone using cobalt. If both triple-dashes were optional, that's also tricky since `---` is markdown for horizontal rule...

**Comment by berkus** [comment]
Both were supported really, so it's not a problem of implementing, it's just a problem on settling on one - and I believe jekyll-style frontmatter is wider present than Cobalt one. However, *sigh*

**Comment by epage** [comment]
Yeah, my thought was to support both.  The only limitation to detecting this situation is if someone has an empty frontmatter and uses `---` later in their document.  Thats a relative low risk that if we switch to encouraging the new form and deprecate the old one, I doubt it'll be a problem.

**Comment by berkus** [comment]
@freiguy1 I believe the `---` should be on separate lines
