### ISSUE TITLE
[Refactor] rename parse_pages to parse_docs

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/cobalt.rs#436]
I'm trying to get knowledge of how cobalt works in order to implement pagination and noticed that `parse_pages` is not really well named (my bad, I was the one who made this function when splitting `build()`).

I think `parse_docs` will be a better name.

In the same idea, the field `pages` in `Collections` is may be not so well chosen, as `context.pages.pages` can show.

I propose to rename it `docs` as well.

**Comment by Geobert** [comment]
We can even change the signature of `parse_pages` as the 1st param is a field of the second parameter

**Comment by Geobert** [comment]
Also, optimization wise, maybe put the call to `Document::parse` inside [the condition](https://github.com/cobalt-org/cobalt.rs/blob/master/src/cobalt.rs#L296) as we keep the parse result only if this condition is verified

**Comment by epage** [comment]
In some respects, pages and docs both work.  In parts of cobalt, I still call them documents for historical reasons but in the user-facing documentation, I refer to them as pages, even if they aren't in the `pages` collection.

**Comment by epage** [comment]
Currently its presented on the site as

> Posts are special pages that live in posts. You can use a different directory for posts with the posts.dir in your _cobalt.yml.

https://cobalt-org.github.io/docs/posts.html

Creating a proposal for the website for terminology would probably be the first thing to do so we refactor the code to match what we're telling users.

**Comment by Geobert** [comment]
Agree, I'll do a pass on the doc and propose a terminology here :)

**Comment by Geobert** [comment]
I propose to change in the documentation:

- under existing `Content` section, create a page called `Documents` which says:

> A document can be a `page`, a  `post` or a `draft`.

then we put below the current `Pages` documentation and then the current `Posts` documentation (including the `Drafts` part)

- Move `Syntax highlighting` on its own page

So in the code we an rename the field `Collection::pages` to `Collection::documents` or `Collection::docs`.
And avoid this weird `pages.pages` and rename the function I'm talking about in the title :)

To optimise the processing a bit, we may pass to `parse_pages` `collection.include_drafts` so we can stop the parsing after the front being created if the flag `front.is_draft` is true.

**Comment by Geobert** [comment]
Are breaking changes allowed? Because to be coherent, I need to rename how we access the collection documents: `collections.posts.pages` become `collections.posts.documents`

**Comment by epage** [comment]
> I propose to change in the documentation:

Why is this here and not in the repo for documentation?

> Are breaking changes allowed? 

We should minimize impact of breaking changes in the format.  That takes a lot more work for people to change than more superficial stuff like configuration or command line arguments.  I've tried to get a lot of breaking changes out of the way earlier.  We should have a solid reasoning behind it for our existing users so they can understand they value they are getting from it rather than coming across churn for churn sake.  We could also consider batching it up like I did before with a migration tool.  That was a lot of work though, especially since I created migration PRs for all of our users listed on the web page.

> EDIT: We can add both of them in a first step to have backward compatibility, with a warning when pages is used instead of documents but I don't know how to put this warning as we can't distinguish from Liquid, can we?

atm we can't do this.  I have a Issue for refactoring variables so that it is behind a Trait and we can on-demand merge variables (so we don't have to merge variables so much, hopefully making things faster).

**Comment by Geobert** [comment]
Ok let's start again as it seems I wasn't clear enough :)

I've started this ticket because while navigating the source code and trying to understand how it works, I found it was quite confusing to have `parse_pages` to parse posts.
Then we have `posts.pages`, I was like "Wait, why we have pages inside posts?". Because here `pages` means documents (as the type suggest it).
I found even more confusing that we have `pages.pages` because the word `pages` means 2 different things here: the 1st is the collection's name, the 2nd is the list that hold the pages inside.

 So I'm okay with the user side terminology you described in the website repo, but I think we need to do something in the code and even the variables.

When I wrote my blog with cobalt, I've never really understood why we have "collections.posts.pages", this `pages` never really makes sense to me, I'm dealing with posts, not pages (as in "everything is pages" in cobalt).

I don't know if I made myself clearer ^^

**Comment by epage** [comment]
> I've started this ticket because while navigating the source code and trying to understand how it works, I found it was quite confusing to have parse_pages to parse posts.

Yes, the current situation is confusing.  My intention was for us to make a decision on the user-facing side first so we can then decide how the code should be handled.  That would be happening in #33.

Once that is resolved, an important thing to keep in mind when refactoring this is where we plan to go: collections.  `parse_pages`, and friends will morph as we more generally processing pages within collections.  I wouldn't worry too much about trying to clear up the intermediate confusion.  We should instead work on getting to where we want to be, #368.  After that, I believe it will be clearer how to clean up this situation.

> When I wrote my blog with cobalt, I've never really understood why we have "collections.posts.pages", this pages never really makes sense to me, I'm dealing with posts, not pages (as in "everything is pages" in cobalt).

Something is needed for `collections.posts.<name>` that is consistent across collections and one of the several generic words needed to be selected.  Interesting, jekyll called them [`Documents`](https://jekyllrb.com/docs/collections/).  I think at the time, I was more looking to [hugo for naming](https://gohugo.io/variables/taxonomy/)

> Maybe I'm missing something but if we do 02a4075
> Doesn't this provide both .pages and .documents to access the same list?

That unconditionally warns, right?  I thought you were referring to warning if the old name is being used

**Comment by Geobert** [comment]
>  My intention was for us to make a decision on the user-facing side

I think that `pages` and `posts` are fine like they are user side.

> We should instead work on getting to where we want to be

From what I read, renaming `Collection::pages` to `Collection::docs` still works semantically speaking

> I think at the time, I was more looking to hugo for naming

It works for Hugo because they're talking about `Data` so they can have `pages` that is the list of the data :)

> That unconditionally warns, right? I thought you were referring to warning if the old name is being used

Yeah right, I though you were answering to the backward compatibility, my bad :)
And yes, I've put the warning to be always shown as like you said, there's no way to do it conditionally.

**Comment by Geobert** [comment]
I still think we have a terminology issue in the code, but this is getting old and is just a question of point of view and not a bug, so let's close this :)
