### ISSUE TITLE
Automatic Generation Of sitemap.xml

### ISSUE THREAD

**Issue by tglman** [cobalt-org/cobalt.rs#452]
Hi,

Would be cool if cobalt could generate the [sitemap.xml](https://en.wikipedia.org/wiki/Sitemaps) with the references to all the pages and resources, in a similar way on how is today is generate the rss.xml, be aware that already exist a crate for generate sitemap [here](https://crates.io/crates/sitemap).

Regards

**Comment by epage** [comment]
Closed by #684
