### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by tglman** [cobalt-org/cobalt.rs#457]
Hi,

From the last build i got two failing tests : 
```
test excerpts_crlf ... FAILED
test excerpts ... FAILED
```

**Comment by epage** [comment]
I just ran the tests and they all passed.

Could you tell me
- What commit of cobalt?
- What OS?
- What version of Rust?

**Comment by tglman** [comment]
Hi,

commit: `395135528de64cf69f0cad769f66e34e268446e0`

```
$ uname -a
Linux  4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
```

```
$ cargo -V
cargo 1.26.0 (0e7c5a931 2018-04-06)

$ rustc -V
rustc 1.26.0 (a77568041 2018-05-07)

```

here is the output of the build: https://gitlab.com/snippets/1719007

Regards

**Comment by epage** [comment]
Sorry I haven't followed up.  I've been completely baffled by this and hoped to have some new insight for how to reproduce this but I don't.

**Comment by Geobert** [comment]
Can't reproduce either, what's your .gitconfig saying on EOL management?

**Comment by anthraxx** [comment]
I seem to be hit by the same issue
environment:
```
$ cargo -V
cargo 1.32.0
$ rustc -V
rustc 1.32.0
```

I'm testing using the following call:
```
cargo test --release --locked
```

A possible reproducer would be via Arch in docker:
```
docker run -it archlinux/base
pacman -Syu base-devel rust
curl "https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/cobalt" > PKGBUILD
$ TODO: adjust sha512sums and pkgver variable in PKGBUILD to latest release
makepkg
```

**Comment by anthraxx** [comment]
There is none, it's a stock git 2.20.1 in a clean build chroot without any config.

**Comment by anthraxx** [comment]
Pull request #597 fixes this issue, its caused by having excerpt posts with the same published_date (9 and 12) which only works if the filesystem on the machine returns the directory listing in the very same order as the test target expects it. Sorting by filename will guarantee that consumption will always be in the same order which makes the output of the static generator reproducible.

**Comment by epage** [comment]
Thanks for figuring that out!

**Comment by Geobert** [comment]
Holy molly, kudos!

**Comment by tglman** [comment]
Tried as well and everything passing ! kudos!

**Comment by anthraxx** [comment]
you're welcome, was fun figuring out :cat:
