### ISSUE TITLE
trait AsciiExt is deprecated

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/cobalt.rs#474]
Since Rust 1.26, we have this warning:
```
warning: use of deprecated item 'std::ascii::AsciiExt': use inherent methods instead
 --> src\syntax_highlight\syntect.rs:2:5
  |
2 | use std::ascii::AsciiExt;
  |     ^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(deprecated)] on by default
```

What is AsciiExt for? If I remove the `use` clause, cobalt compile just fine.

**Comment by epage** [comment]
Its an extension trait for strings.  It added some functionality that is now directly available on strings, making it redundant.

**Comment by Geobert** [comment]
So the fix is to simply remove the `use` clause then? If so, I'll do a quick PR for that :)

**Comment by epage** [comment]
Yup

**Comment by Geobert** [comment]
it's ok now
