### ISSUE TITLE
Passing parameters to includes

### ISSUE THREAD

**Issue by bytesnake** [cobalt-org/cobalt.rs#494]
Hey,
I'm trying to create a snippet for a synopsis. My blog is written in different languages, so it would be nice to pass an language argument. Apparently Cobalt doesn't support something like `{{ include.lang }}` inside the _includes folder. (taken from https://jekyllrb.com/docs/includes/) Am I doing something wrong or is the implementation just not complete?
Otherwise Cobalt is really helpful, thanks for maintaining it :)

**Comment by epage** [comment]
atm we do not support passing variables to an `include`, see https://github.com/cobalt-org/liquid-rust/issues/143

This can be worked around by
- Putting a variable in your `data` section of your frontmatter and accessing it as `page.data.`
- Using `assign` to create the variable

These of course aren't scoped to the `include` but that shouldn't usually be a problem.
