### ISSUE TITLE
Sass not compiling

### ISSUE THREAD

**Issue by jhartwell** [cobalt-org/cobalt.rs#495]
I'm running Cobalt 0.12.2 built locally with sass feature enabled on macOS 10.13.6. My repo is located https://github.com/Haml-rs/hamlrs-web/tree/cobalt-sass-issue

When I try to run cobalt build or cobalt serve my sass files in the _sass directory are not being compiled. I have tried using the scss and sass extensions and they are both ignored.

**Comment by epage** [comment]
From what I can tell, all of your sass is in `_sass`.  Instead, that folder is meant to be just the snippets

> Sass snippets that can be imported into your .scss files.

https://cobalt-org.github.io/docs/directory.html

I suspect we do not make this clear enough but the issue is deciding how to make it clearer

**Comment by jhartwell** [comment]
@epage thanks for the response. I saw the snippets but wasn't sure what exactly that meant in the sass realm as sass allows for importing anyways. Is there a particular reason that _sass would be only for snippets and not where to put all sass items?

**Comment by epage** [comment]
cobalt needs
- know which sass files are top-level
- what the output path / permalink is for them

So for consistency, sass files are treated like liquid or anything else.

The sass files you include are in a hidden folder to keep them from being processed.

**Comment by jhartwell** [comment]
I see, thanks for your help @epage it is much appreciated. Now that I'm doing things correctly by keeping main sass files out of _sass the files are actually being generated.
