### ISSUE TITLE
Add a serve(r) command

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#50]
We should enable people to run a local website server with a command like `cobalt serve` or `cobalt server` or `cobalt start`

**Comment by tak1n** [comment]
Would be cool yes, you want to use nickel.rs, iron or smth different for this?

If we know what we want to use there I will look at this feature.

**Comment by johannhof** [comment]
Well nickel is definitely a bit too much features, we only want simple static file serving. Iron might do, although it might be possible in an even simpler way, maybe using hyper.

There's a static file serving plugin for Iron: https://github.com/iron/staticfile

**Comment by tak1n** [comment]
https://github.com/nickel-org/nickel.rs/blob/master/examples/static_files.rs

**Comment by johannhof** [comment]
Mmh yeah that might work as well.
