### ISSUE TITLE
Clarify the syntax within a blog post

### ISSUE THREAD

**Issue by Susurrus** [cobalt-org/cobalt.rs#56]
I think this only supports plain-text for now, but if it supports rST or Markdown it should be explicitly noted in the README.

**Comment by johannhof** [comment]
You're right, we don't mention it but we do support Markdown. Any `.md` file will be transformed by [markdown.rs](https://github.com/johannhof/markdown.rs). Note that I wrote this library on my own back in the very early days when there was no Rust alternative and some things are still missing. 

Before we declare "official" markdown support we should switch to a more complete implementation like [pulldown-cmark](https://github.com/google/pulldown-cmark).

**Comment by johannhof** [comment]
I think we can close this
