### ISSUE TITLE
Build fails if "dest" does not exist.

### ISSUE THREAD

**Issue by Sean1708** [cobalt-org/cobalt.rs#59]
It's obviously not a huge issue but it is a bit inconvenient.

Can be reproduced from a clean working directory by:

```console
$ ls -A
$ cobalt -v
0.2.0
$ cat > .cobalt.yml
source: src
dest: public
$ mkdir src
$ cat > src/index.html
<!DOCTYPE html>
<html>
<body>
<h1>some title</h1>
</body>
</html>
$ cobalt build
[info]   Using config file ./.cobalt.yml
[info]   Building from src into public
[info]   Copying remaining assets
[error]  error: Could not copy "src/index.html"
[error]  Build not successful
$ mkdir public
$ cobalt build
[info]   Using config file ./.cobalt.yml
[info]   Building from src into public
[info]   Copying remaining assets
[info]   Build successful
```

**Comment by Sean1708** [comment]
Actually, looking further into this it appears to be a problem with all directories.

```console
$ ls -A
$cat > .cobalt.yml
source: src
dest: public
$ mkdir src
$ cat > src/index.html
<!DOCTYPE html>
<html>
<body>
<h1>some title</h1>
</body>
</html>
$ mkdir src/style
$ cat > src/style/main.css
body {
    color: #333333;
}
$ cobalt build --trace
[info]   Using config file ./.cobalt.yml
[info]   Building from src into public
[trace]  Build configuration: Config { source: "src", dest: "public", layouts: "_layouts", posts: "_posts", template_extensions: ["tpl", "md", "liquid"], rss: None, name: None, description: None, link: None }
[debug]  Layouts directory: "src/_layouts"
[debug]  Posts directory: "src/_posts"
[info]   Copying remaining assets
[error]  error: Could not copy "src/index.html"
[error]  Build not successful
$ mkdir public                                                                                                      1 ↵
$ cobalt build --trace
[info]   Using config file ./.cobalt.yml
[info]   Building from src into public
[trace]  Build configuration: Config { source: "src", dest: "public", layouts: "_layouts", posts: "_posts", template_extensions: ["tpl", "md", "liquid"], rss: None, name: None, description: None, link: None }
[debug]  Layouts directory: "src/_layouts"
[debug]  Posts directory: "src/_posts"
[info]   Copying remaining assets
[debug]  Copied "src/index.html" to "public/index.html"
[error]  error: Could not copy "src/style/main.css"
[error]  Build not successful
$ mkdir public/style                                                                                                1 ↵
$ cobalt build --trace
[info]   Using config file ./.cobalt.yml
[info]   Building from src into public
[trace]  Build configuration: Config { source: "src", dest: "public", layouts: "_layouts", posts: "_posts", template_extensions: ["tpl", "md", "liquid"], rss: None, name: None, description: None, link: None }
[debug]  Layouts directory: "src/_layouts"
[debug]  Posts directory: "src/_posts"
[info]   Copying remaining assets
[debug]  Copied "src/index.html" to "public/index.html"
[debug]  Copied "src/style/main.css" to "public/style/main.css"
[info]   Build successful
```

**Comment by LucioFranco** [comment]
I can confirm that I get the same issue. I have to create the directory myself. Seems like this could be an easy fix.

**Comment by johannhof** [comment]
Huh, that's a pretty glaring bug. I'm pretty sure we `mkdirp` before copying. Weird. I'll look into it, thanks for reporting.

**Comment by Sean1708** [comment]
I think it might have been caused by 4502ce2840b6abdc8852029f097ea66f08ca66a1. Originally [this](4502ce2840b6abdc8852029f097ea66f08ca66a1) for loop hit every entry and therefore also picked up directories [which were checked here](https://github.com/cobalt-org/cobalt.rs/commit/4502ce2840b6abdc8852029f097ea66f08ca66a1#diff-1adad72e4e1dbe7019b775a6acb9455aR98). However with the new macro, [directories are skipped](https://github.com/cobalt-org/cobalt.rs/commit/4502ce2840b6abdc8852029f097ea66f08ca66a1#diff-1adad72e4e1dbe7019b775a6acb9455aR21) so [this condition](https://github.com/cobalt-org/cobalt.rs/commit/4502ce2840b6abdc8852029f097ea66f08ca66a1#diff-1adad72e4e1dbe7019b775a6acb9455aR98) always evaluates false (and therefore never creates the directories).

Having said that, I've only been able to have a cursory glance on the way home, so I could easily have missed something.

**Comment by johannhof** [comment]
@Sean1708 Yeah, I'm pretty sure you're right about that. Damn, this could've been tested.

If you or @LucioFranco want to fix it yourself, please go ahead. I'm not gonna be near a computer for the next two days. The fix should be pretty trivial, you could either not use the walker macro for copying files, or create directories before copying files instead (maybe the latter is the best solution).

It would also be great to have a small integration test that makes sure nested directories are copied correctly.

If you don't find the time I'll take care of it. :)

Thanks!

**Comment by LucioFranco** [comment]
@johannhof @Sean1708 I might take a crack at it tonight

**Comment by Sean1708** [comment]
Works perfectly for me now, thanks!

**Comment by tak1n** [comment]
Glad to hear that and thanks for opening the issue.
Also thanks again to @LucioFranco for fixing that :)
