### ISSUE TITLE
Marking post as a draft does not make it private

### ISSUE THREAD

**Issue by eloydegen** [cobalt-org/cobalt.rs#593]
When a post is being published and afterwards is changed back to draft status, the link is being removed from the index page, which is the expected behavior. However, it is still accessible through a direct link.

**Comment by epage** [comment]
Could you list what steps you are using?

Please include if this on your local system, when using our [deployment instructions](https://cobalt-org.github.io/docs/deployment/), or some other means.

My guess is that we need to add a `cobalt clean` to our deployment instructions.

**Comment by eloydegen** [comment]
Ah yes, I missed that, that fixed it!
