### ISSUE TITLE
Environment Path Setup needs to be indicated in Docs

### ISSUE THREAD

**Issue by sudopower** [cobalt-org/cobalt.rs#604]
It may seem obvious but is really nice for new comers.

**Comment by sudopower** [comment]
It may seem obvious but is really nice for new comers.

**Comment by epage** [comment]
Thanks for being interested! Sorry you had to deal with this hurdle.

To help ensure we are on the same page and we solve the right problem, could you clarify what path setup stuff you are talking about?

**Comment by sudopower** [comment]
Thanks you for the prompt reply, I am talking about the environment path to cobalt.exe, when we call cobalt init or cobalt build, i guess it's cobalt.exe that's being called on windows system. Windows report to have not found cobalt command so I guessed it doesn't recognize it and hence pointed it to cobalt executable by defining it's path in the OS's environment path variable. It fixed my issue on my office laptop and PC which run windows. Sorry if I'm being too elaborative I'm kind of new to the issues and discussions thing. Thought this might help someone else like me...

**Comment by epage** [comment]
So let me step back and see if I understand.  On Windows, you downloaded cobalt zip from github, unzipped it, and was left with a binary in a "random" location that made it so it wasn't in your PATH for easy access?

**Comment by sudopower** [comment]
### Yes, it is fixed now 👍  

I followed the instructions in the [docs](http://cobalt-org.github.io/docs/install/) and performed following actions.

1. Cloned the Repository inside of my projects folder.
2. Entered `cargo build --release --no-default-features`.
3. Then ran the tests, which reported successful build.
4. Entered into my blog directory and entered `cobalt init`.
5. It reported 
> cobalt: command not found
6. I added `my_drive/projects/cobalt.rs/target/release` to path 
which fixed the problem !
