### ISSUE TITLE
Get permalink for another page or post

### ISSUE THREAD

**Issue by ticky** [cobalt-org/cobalt.rs#607]
Jekyll includes [a `post_url` tag](https://github.com/jekyll/jekyll/blob/7ee2e26d6c9eb9523195521e8bece7908cf83eac/lib/jekyll/tags/post_url.rb), which fetches the URL to another post by on-disk filename, this would be useful in Cobalt too!

**Comment by ticky** [comment]
I think this is technically a dupe of #440!

**Comment by epage** [comment]
Agreed. We've started talking about this on #440. We are looking at using markdown anchors but a tag is another possible option.
