### ISSUE TITLE
Recursively extend layouts

### ISSUE THREAD

**Issue by Aceeri** [cobalt-org/cobalt.rs#61]
Would it be possible to have the ability to recursively extend layouts? It would help out a lot if you wanted to having some navigation bar on all your pages, but then extend that navigation bar with another template.

**Comment by LucioFranco** [comment]
+1

**Comment by tak1n** [comment]
This would be a nice feature, but I think this is done via liquid include tag.
I'm not sure if liquid-rust supports that yet.


cc @johannhof

**Comment by tak1n** [comment]
I opened https://github.com/cobalt-org/liquid-rust/issues/21 to keep track of missing tags.

**Comment by LucioFranco** [comment]
@tak1n @johannhof I am very interested in this feature. How hard would it be to implement. If it is not too bad I might try and take a crack at it.

**Comment by tak1n** [comment]
@LucioFranco I'm not that comfortable either with liquid-rust yet as @johannhof did most of the work here. 

But I think you should get a working prototype with this instructions: https://github.com/cobalt-org/liquid-rust#create-your-own-tags.

**Comment by johannhof** [comment]
Yes, as I mentioned in the liquid thread, the current way Cobalt hacks together the templates is dead ugly, and I'd love to build a proper system inside the Liquid language and a Liquid plugin that provides even more functionality for including files/partials.

@LucioFranco if you're interested in implementing `include` in Liquid you can make a short comment at https://github.com/cobalt-org/liquid-rust/issues/21. You will find helpful instructions in the README and by looking at the existing tags. If you need help, just drop by IRC or Gitter and we'll try to help you out. :)

**Comment by johannhof** [comment]
I'm gonna close this because we just bumped Liquid to 0.6 with `include` support, feel free to comment/reopen if that's not sufficient.
