### ISSUE TITLE
[feature request] querying pages

### ISSUE THREAD

**Issue by chpio** [cobalt-org/cobalt.rs#619]
Hi,

i would like to query other pages, say i want to generate multiple navs for my site, like a side bar with some content, and then a header nav bar with links to other pages. Is this something you want to offer, as it seems that cobalt is very blog oriented right now?

i think GraphQL would be a good choice as a query language.

**Comment by epage** [comment]
Could you elaborate on how you might expect a side bar or nav bar to work?  How might you integrate GraphQL into a static site generator?

Queries we support today
- Iterating over all posts, see [collections.posts](https://cobalt-org.github.io/docs/variables/)
  - When we add custom collections, we'll expand this to cover them as well

Planned
- #440 getting links from a file path

Other static site generators also support the concept of "menus" which is very related to indexes (#395).

If navigation was defined via categories and if we offered a way to walk the categories, that could possibly simplify nav bars.

**Comment by chpio** [comment]
> If navigation was defined via categories and if we offered a way to walk the categories, that could possibly simplify nav bars.

Yeah, it might. But it would be to inflexible for my taste.

> How might you integrate GraphQL into a static site generator?

I guess it would be much better to make a framework, that would allow to do GraphQL queries on data, and add the things like the static page tree as a driver to it. But i guess it's not what you would like to make cobalt into?

Also i had this idea for a long time, that a query could be parsed beforehand (at template compile time), then reversed. We could use it to impl incremental rendering, so if a page changes, we would reverse match the querying pages and only rerender those.

1. We would reverse match the changed page to queries (those are part of templates, thus we would actually match for templates) for static query conditions (like queries for some specific page attribute)
2. then reverse match all pages, that are using that particular template, in the context of the page, so that we can evaluate the dynamic conditions (like the position of the page in the page tree or something like id queries). As we are already precompiling the templates, we could separate the code for the computation of the dynamic conditions from the rendering.

ps: sorry, im sick (so it's hard to concentrate) & my native lang isn't english...

**Comment by epage** [comment]
Thanks for clarifying.

One thought I had is if we created a consistent data model for the site source, we could allow a GraphQL block.  It could look something like this:

```liquid
{% graphql var_name %}
query
{% content %}
... evaluate with queries result assigned into var_name ...
{% endgraphql %}
```

It'd be a big under taking to make the data available to provide graphql bindings though it is interesting blurring the lines more between a static and dynamic site.

Once I finish with some distractions, I plan to get back to #560.  That'll make all of the data accessible.  The thing after that would be to make an adapter to connect to some graphql library.

Random thoughts
- It'd be a lot of work on its own to get the graphql bindings even once we have #560 
- It'd be a lot more powerful than our work on #395 
- It'd be less out of the box friendly than #395 

One of the big challenges I foresee is that our data model would be invisible to the user.  I've read about but not used GraphQL yet, so unsure if there is some kind of schema format we could export.  We could then also have a command line mode that took in queries and returned the results, giving a repl like experience.

@Geobert from the perspective of your index work, any thoughts?

**Comment by epage** [comment]
> then reverse match all pages, that are using that particular template, in the context of the page, so that we can evaluate the dynamic conditions (like the position of the page in the page tree or something like id queries). As we are already precompiling the templates, we could separate the code for the computation of the dynamic conditions from the rendering.

This is something I've been giving thought already.  First, we need to re-work our data pipeline so its easier to refactor.  After that, it should be easier for us to play with incremental evaluation.  I talk a little about this in #560 with the consideration of Salsa though I hope we can get similar behavior with an ECS.  We can do some primitive incremental evaluation without any fancy work.  To make it smarter, we'll probably need help from the liquid implementation.

**Comment by Geobert** [comment]
I like the idea of incremental build. I need to dig into Graphql, never heard of it before :)

**Comment by epage** [comment]
Hmm, just realized, doing GraphQL inside of Liquid would mean we couldn't paginate with it.  We'd need it in the frontmatter as a way to setup index/pagination.

Even if we do that, then how do we handle nested indexes?

While we get a little more flexibility with GraphQL, we get constrained in other ways.  Unsure of the value add relative to the implementation time.

**Comment by epage** [comment]
To be clear, if someone names a use case where GraphQL would help, that makes a big difference.
