### ISSUE TITLE
panic "not a char boundary"

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/cobalt.rs#633]
Using master Apr 7, 2019 
When writing:
```
[« Blurry Eyes »][blurry_eyes] est assez représentatif de
ce peut faire le bassiste (cliquez sur [le lien][blurry_eyes], elle n’est pas intégrable).
```

I got this error:
```
thread 'main' panicked at 'byte index 19 is not a char boundary; it is inside '»' (bytes 18..20) of `[« Blurry Eyes »][blurry_eyes] est assez représentatif de
ce peut faire le bassiste (cliquez sur [le lien][blurry_eyes], elle n’est pas intégrable).

« Pieces », Une jolie balade :

<div class="embed-video"><iframe src="https://www.youtube.com`[...]', src\libcore\str\mod.rs:2102:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

After some try, it seems that using ` »` inside a `[]` is causing the error.
Note that the space before `»` is a non-breakable space.
I've tried: 
* `space»][link_ref]` -> working
* `][link_ref]nbsp»` -> working
* `nbsp"][link_ref]` -> working
* `nbsp»][link_ref]` -> broken

EDIT:
* reverting to c4e318b - Merge pull request #628 from cobalt-org/dependabot/cargo/syntect-3.2.0
works, so I suspect the new markdown parser
* created upstream bug: https://github.com/raphlinus/pulldown-cmark/issues/261

**Comment by epage** [comment]
Thanks for digging into this, including finding its an issue with pulldown-cmark.

Would you prefer we sit on this until they have a fix for us to upgrade to or to rollback the version of pulldown-cmark until the fix is available?

**Comment by Geobert** [comment]
We can wait for the bug fix :) I have only one file with this error (lucky to find this bug!!) And I have a workaround if I need to rebuild :)
