### ISSUE TITLE
Support for custom permalinks

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/cobalt.rs#66]
It would be nice to be able to have permalinks similar to what [jekyll](https://jekyllrb.com/docs/permalinks/) does.

**Comment by tak1n** [comment]
This should be definitely something we should provide in future, yes.
As you're a little bit active on liquid and cobalt do you mind to join the gitter channel? https://gitter.im/cobalt-org/cobalt.rs

I want to start a discussion about where cobalt should go and get a vague roadmap.
Thx again for your contributions to cobalt and liquid-rust and hopefully we chat soon in the gitter channel :)

**Comment by LucioFranco** [comment]
We should track this issue with #72.

**Comment by LucioFranco** [comment]
#107 resolves this. We will create another issue to track smaller issues with custom paths.
