### ISSUE TITLE
Skeleton generator

### ISSUE THREAD

**Issue by tak1n** [cobalt-org/cobalt.rs#67]
Cobalt should provide a basic command for creating a new project with config file and everything setup.

```
cobalt new MyBlog
```

**Comment by drusellers** [comment]
Yes, please. I just pulled down the project and I'm not entirely sure where to start. Even a basic skeleton on the README.md would be nice to see.

**Comment by LucioFranco** [comment]
@drusellers [amethyst/website](https://github.com/amethyst/website) is a very good example. I also have a somewhat skeleton project [here](https://github.com/LucioFranco/cobalt-skelton-project) but I don't think it will work with the watch command right now. But we do need to add somemore to the `README.md`.
