### ISSUE TITLE
Cobalt hangs on Ctrl-C

### ISSUE THREAD

**Issue by brown121407** [cobalt-org/cobalt.rs#699]
With 0.15.6, I can't close `cobalt serve` anymore. It doesn't respond to Ctrl-C, nor to SIGINT or SIGTERM, only to SIGKILL.

Here's a log file when I started the server and tried to close it, I hope it contains something useful:
https://paste.sr.ht/%7Ebrown121407/cb2fe80a60941a9dff7e40678101d770509958e6

**Comment by cup** [comment]
https://github.com/getzola/zola/issues/893

**Comment by epage** [comment]
I found the problem and have a fix.

The question is how to distribute it.  I'm working on a major re-work of cobalt where I also break compatibility.  I assume there is enough interest in this fix to create a release branch to get this out?

**Comment by epage** [comment]
Forgot to note that #710 fixes this.

**Comment by astraw** [comment]
I just hit this as well. Since this is a regression, it would indeed be great to get a quick fix which does not break compatibility. I'm going to stick with 0.15.5 for now.

**Comment by epage** [comment]
Hey all, sorry for taking way too long on this.  Would someone want to do a sanity check on `master` before I release this?

**Comment by astraw** [comment]
I just built master (at e9e31fabd48740f5ced3664a0018f51cf2e98ebb) and ran a quick check. Without intensive double checking, everything seems to work for me, including Ctrl-C again. So this issue seems fixed.

Thanks for your work on cobalt - it is very useful!

**Comment by epage** [comment]
Cut a new release.  Once the CI is done, a pre-built binary should be up.

As an FYI, what I was busy with instead of this was overhauling liquid.  The goal for the next release
- Getting the API closer to a 1.0 state
- Performance improvements
- Support for `variable.size`.
