### ISSUE TITLE
Use config defaults in getopts default

### ISSUE THREAD

**Issue by tak1n** [cobalt-org/cobalt.rs#71]
Currently in https://github.com/cobalt-org/cobalt.rs/blob/master/src/main.rs#L26 the defaults for some configuration options are hardcoded. 

We should use the defaults from https://github.com/cobalt-org/cobalt.rs/blob/master/src/config.rs#L22 so we have 1 place where we change defaults.

**Comment by epage** [comment]
Closing.  This is now a moot point because the command line flags are a lot more limited.
