### ISSUE TITLE
How to select template with `cobalt new`?

### ISSUE THREAD

**Issue by SuperPrower** [cobalt-org/cobalt.rs#712]
Let's say I created a `_default/special_posts.md`, which I want to base some on posts on. How can I specify using it instead of `_default/posts.md`? I think that #355 does that, but I'm not sure I follow the logic. I tried doing `cobalt new "Test" -f special_posts/`, but it just created a post based on `_default/pages.md` (which makes sense since it isn't in the posts dir).

Thanks in advance.

**Comment by epage** [comment]
Currently, cobalt is hardcoded to supporting `_defaults/posts.<ext>` and `_defaults/pages.<ext>`.

In part, this was trying to balance customization with simplicity and intuitiveness.  I'm open to ideas on what people will want to see though.

**Comment by SuperPrower** [comment]
Oh, okay. Again, notes in #355 made it seem like cobalt can derive template name from the path (which is kinda true, just for the those two names). 

In my opinion, this kind of implicit deriving is not very intuitive: for example, you follow the getting started guide trying to write a new post but get the `pages` template instead of `posts`. My proposal would be like following (I don't know enough rust (just yet) to make a pull request on this): keep two base templates (I can understand why you would want just them), but instead of deriving the template based on the path, make it a flag for a `new` command - `--post` or `--page`

**Comment by epage** [comment]
So to further clarify on this.

The long term goal of cobalt is to add support for "collections".  "posts" is a built-in collection.  By generalizing it, we could define separate "talks" from "posts" or anything else someone might want.  Before I fully implement collections, I am planning to re-architect cobalt using the ECS architecture which should make collections a lot easier to implement.

The `new` template is based on which "collection" you are creating it for (until full collection support, we only have "posts" and "pages").  The idea is that a generic page, a post, a talk, etc are all very different and so the template should be specialized based on the collection.  We can infer the collection from the path and don't need collection flags (and collection fags would need to be generic for when we support user-defined collections).

There are chances that
- A user might want to share a template across collections (probably too small of a use case?)
- A user might want more than one template for a given collection (unsure of the size of this use case).

So the question would be how to generalize this, if needed.  Some examples include
- Allowing freely specifying the template, relying on the user to get it right
- Have per-collection additional templates

**Comment by epage** [comment]
Going to go ahead and close this out as the collection is the unit of template selection

**Comment by SuperPrower** [comment]
Oh, that's good. You refer to layouts - https://cobalt-org.github.io/docs/layouts/ - correct?

**Comment by epage** [comment]
I'm referring to collections of which we currently only have `pages` and `posts` but will add support for user-defined ones (https://github.com/cobalt-org/cobalt.rs/issues/368).
