### ISSUE TITLE
[tracking] Jekyll compatibility

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/cobalt.rs#72]
Having tons of similarities to Jekyll (Liquid templates, front matter, YAML), it would be a waste not to maintain backwards compatibility. This issue is intended to track other issues that ensure we get compatible.

**Comment by epage** [comment]
Being a superset of Jekyll means we also have to inherit some of the downsides.  A jekyll converter, like is being started in #289 might be a nicer way to go.

**Comment by Geobert** [comment]
So shall we close this one? As the work for the jekyll converter is tracked elsewhere :)

**Comment by epage** [comment]
Sure.  See #276.
