### ISSUE TITLE
Windows zip of v0.15.7 and later is empty

### ISSUE THREAD

**Issue by inosik** [cobalt-org/cobalt.rs#722]
![2020-02-11_10-19-45](https://user-images.githubusercontent.com/11393003/74223949-16e4ac80-4cb8-11ea-8a2a-2cb580ef3456.png)

**Comment by epage** [comment]
Yeah, started looking into this but haven't made much progress yet.  The error is at https://dev.azure.com/cobalt-org/cobalt-org/_build/results?buildId=299&view=logs&j=9c50dd2c-b7db-5d15-01cc-66c745e06098&t=e685b674-06de-51f2-49d6-9056a7e1fb88 that is causing this.

Thanks for opening an issue to track this!

**Comment by epage** [comment]
I think I've got a fix up and tagged.  We'll see once the CI comnpletes.

**Comment by epage** [comment]
Looks like we are uploading binaries again!

See https://github.com/cobalt-org/cobalt.rs/releases/tag/v0.15.9

**Comment by inosik** [comment]
Thanks for taking care of this!
