### ISSUE TITLE
Suggestion: enable more clippy warnings

### ISSUE THREAD

**Issue by rotty** [cobalt-org/cobalt.rs#726]
When running my usual clippy invocation, as shown below, I noticed it spits out quite a few suggestions for improvements, which, at a first glance, would improve code quality a small bit, if applied. I would volunteer to provide a PR that changes the CI configuration accordingly, after fixing all warnings.

```
cargo clippy --all-targets --all-features -- -D warnings
```

**Comment by epage** [comment]
That'd be great, thanks!
