### ISSUE TITLE
Serve command doesn't send MIME types

### ISSUE THREAD

**Issue by olanod** [cobalt-org/cobalt.rs#732]
I guess it's a regression after switching to tiny-http, my scripts fail to load because browsers like content being served to have a MIME type. So no `cobalt serve` in my workflow for now :/

**Comment by epage** [comment]
Do you have a reproduction case I can use for testing fixes?

**Comment by epage** [comment]
Alternatively, you can try my PR to see if it fixes it for you
https://github.com/cobalt-org/cobalt.rs/pull/733

**Comment by olanod** [comment]
Seems to be working like a charm :wink:
