### ISSUE TITLE
Proper Relative Paths

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/cobalt.rs#74]
We should handle relative paths better. @tak1n suggested that we use the `build` dir to be the base of the relative path. I think this would be good and allow us to pass that value to `liquid-rust` so that the template paths do not need to be very long.

Example:
@tak1n 
`cobalt build -s src/ -d /wherever/I/want -c .my_config.yml`
It should respect the source directory and search for the config file in src/
currently as far as I know you have to do following
`cobalt build -s src/ -d /what/what -c src/.my_config.yml`

**Comment by LucioFranco** [comment]
This issue is connected to [#30](https://github.com/cobalt-org/liquid-rust/pull/30). Once that gets merged we can commence on this.

**Comment by LucioFranco** [comment]
@tak1n I do not think we should have the config loaded from the source directory. Some people may want to have their config outside of their source dir. It may be better to just let them define it from where they run `cobalt`. What do you think?

**Comment by johannhof** [comment]
I agree, that's how I've setup my blog for example
