### ISSUE TITLE
Add information to the Wiki

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/cobalt.rs#78]
I think we should start adding detailed info on the wiki. This issue is to keep track of our progress.

The wiki should contain:
- [x] CLI usage
- [x] Config setup
- [ ] Avaliable tags and how to use them.
- [ ] Avaliable variables and how to use them. Example: list what variables are available to use in an `if` block.

If there are any other let me know and I will add it to the list.

**Comment by tak1n** [comment]
@LucioFranco I thought we agreed on starting a seperate documentation site?

I created a repo for that: https://github.com/cobalt-org/website

**Comment by LucioFranco** [comment]
@tak1n I was still thinking about that. But I feel it may be good to just have some basic info for the moment while we figure out the website. For someone who is new to cobalt and tries to setup a site right now. It is confusing to figure out the tags and variables they can use. So I was just thinking that it may be useful to have basic information on the wiki then expand on that information on the website with way more detail. What do you think?

**Comment by tak1n** [comment]
@LucioFranco good point 
Feel free to create pages at the wiki :smile:

**Comment by epage** [comment]
Addressed by https://github.com/cobalt-org/cobalt-org.github.io/pull/17
