### ISSUE TITLE
Create new post -> publish results in error

### ISSUE THREAD

**Issue by Newbytee** [cobalt-org/cobalt.rs#788]
# System info

OS: Fedora 32
File system: ext4
Rust version: 1.44, 1.45.1 (both tested)
Cobalt version: 0.16.1 (built from source)

# Description

I was looking for a static site generator and decided to give Cobalt a try, and as I prefer to install things via my package manager (and my system's one does not have cobalt packaged) I installed it via cargo using `cargo install cobalt-bin`. I subsequently went on to create a website using Cobalt, but quickly ran into the issue that Cobalt would tell me `Error: serve command failed` when I attempted to serve the website via `cobalt serve`, with the reason being that it failed to parse my newly created markdown file. File can be found inside the archive attached below. The reason for the failure to parse was "caused by input contains invalid characters at line 1 column 6", which from what I understand would point to the `:` assuming the line numbers are 0-indexed. Very odd. I'm not sure what to make of this. On one hand it feels like I'm doing something incredibly stupid here which I don't realise given I haven't done anything unusual to my knowledge, but on the other I just followed the instructions with the exception that I installed via cargo as opposed to the suggested methods.

[testus.tar.gz](https://github.com/cobalt-org/cobalt.rs/files/5010998/testus.tar.gz)

# Reproduction

1. Create a new post via `cobalt new test`
2. Publish this post via `cobalt publish test.md`
3. Serve your static website via `cobalt serve`

**Comment by epage** [comment]
The bad error reporting is recorded in #782.  The date is `2020-08-01 16:24:03.037116292 +00:00` but needs to be `2016-02-16 10:00:00 +0100`

Somehow `cargo publish` is generating a bad date format

**Comment by epage** [comment]
0.16.3 is now out and should have the fix for this
