### ISSUE TITLE
Incorrect python3 highlighting

### ISSUE THREAD

**Issue by krtab** [cobalt-org/cobalt.rs#802]
Hi,

Adding the following python code anywhere in markdown code blocks

```py3
def f(x):
  pass

def g(x):
  pass
```

is incorrectly highlighted: the second `def` is on red background, which it shouldn't.

![screen](https://user-images.githubusercontent.com/53921575/95910481-6ed03780-0da0-11eb-8220-eb7c3a14b3fc.png)

Thanks for your work, and let me know if I can help.

**Comment by krtab** [comment]
Note that this is not a syntect bug, as `synhtml` in the syntect examples gives me:
![screen_001](https://user-images.githubusercontent.com/53921575/95912535-3847ec00-0da3-11eb-8b36-67ce67162480.png)

**Comment by krtab** [comment]
I would have thought something to do with how you pass the text to syntect, like if you trim `\n` or trailing whitespaces maybe. I tried reading `syntect.rs` but got lost. Anyhow, thanks for your quick response.

**Comment by epage** [comment]
Just confirmed: went with default features and it changed in appearance

**Comment by epage** [comment]
Looks like this is `regex-onig` (C) vs `regex-fancy` (Rust)

I'm going to go create an issue in syntect about this.  I'm hesitant to switch because we've had a lot of build issues with various C libraries.

**Comment by epage** [comment]
Issue created over at syntect.  I would be interested to know your thoughts on this for if I should attempt to go back to `regex-onig`.

**Comment by krtab** [comment]
To be honest I have no idea, I discovered syntect yesterday investigating this bug.

**Comment by epage** [comment]
The fix is in 0.16.4

**Comment by krtab** [comment]
Thanks!
