### ISSUE TITLE
Any interest in a contribution to add vimwiki as a source format?

### ISSUE THREAD

**Issue by chipsenkbeil** [cobalt-org/cobalt.rs#817]
As the title implies, curious if there's any interest in supporting other source formats other than markdown. I'd write the contribution myself, so no need to contribute cycles beyond review.

I saw https://github.com/cobalt-org/cobalt.rs/issues/272 from three years back mentioned the enum for source formats, which I see is used here for raw/markdown: https://github.com/cobalt-org/cobalt.rs/blob/master/src/document.rs#L301

### vimwiki

I've been working on [vimwiki-rs](https://github.com/chipsenkbeil/vimwiki-rs) (runtime & compile-time parsing of the vimwiki language) for a little while in conjunction with formally defining a specification for the language over at https://github.com/vimwiki/vimwiki/pull/1025, which just merged. The language has single and multi-line comments, which is where I'd stuff in metadata.

I've got on my list to support an export to typed html and/or html string, but not sure if there would be interest in supporting that with cobalt (maybe behind a feature gate).

My interest is enabling more users, including myself, to have the option to use vimwiki as a markup language given I already use it for note taking.

**Comment by epage** [comment]
Yes, I am interested in new formats being added and the benefit is it doesn't conflict with the current slow down of cobalt.  I've been running into limitations with the current architecture, so I've been playing with another one (in the `next` branch).  Well, there is another slow down, I'm trying to get another project off my plate so been putting work on it to wrap it up.

> The language has single and multi-line comments, which is where I'd stuff in metadata.

This is the interesting part to figure out.  At the moment, all documents are YAML streams with the yaml part being the metadata and the content after the stream being the document body.  The file extension provides a default for `SourceFormat` which describes the document body but the canonical definition is from within the metadata.  We could evaluate taking the `SourceFormat` only from the extension and having a `SourceFormat` specific way of extracting metadata.  I would be interested to hear how the Yaml metadata would play with vimwiki to see better understand the trade offs.

An example of the flexibility of ignoring the file extension is where I do it [for custom markdown handling](https://raw.githubusercontent.com/epage/epage.github.io/source/blog/talks/2018-06-14-rust-for-clis.md)

**Comment by chipsenkbeil** [comment]
It sounds like you've described the options already: parse YAML with the document body being parsed by the metadata `SourceFormat` or rely on the format being detected by the extension with metadata being parsed using some language-specific means.

For vimwiki, there are two kinds of comments:

```
%% a single line comment that begins with two percent signs

%%+ a multi-line comment that starts with two percent signs and a plus 
and then ends with a plus and two percent signs +%%
```

Easiest way to do this in vimwiki would be to parse the file and examine the comments for some metadata format such as YAML. You could always make it be the first comment.

Personally, the YAML stream sound fine and is language-agnostic.

A separate challenge is handling the liquid template evaluation. My understanding is that you can have a markdown file that has liquid objects that get parsed before converting to HTML, is that right?

If so, vimwiki has conflicting syntax with liquid's `{{ page.title }}` object syntax. A transclusion link, which is where you import one file into another, has the format `{{file:../../images/vimwiki_logo.png}}` or `{{http://vimwiki.googlecode.com/hg/images/vimwiki_logo.png}}`. I suppose determining if the inner content of `{{...}}` is a link or an object would be required to make sure you don't break a link that way.

Alternatively, just indicate that transclusion links aren't supported by cobalt, which also makes sense to me.

**Comment by epage** [comment]
> A separate challenge is handling the liquid template evaluation. My understanding is that you can have a markdown file that has liquid objects that get parsed before converting to HTML, is that right?

Well, good news
- Users can disable liquid on a per-file basis or change the global default
- In the `next` branch, I plan to change the default for liquid to be off-by-default.  I got the idea from zola.  The theory is that layout needs Liquid's power but rarely does a page body need Liquid's power.  This would greatly speed up processing.

> I suppose determining if the inner content of {{...}} is a link or an object would be required to make sure you don't break a link that way.

Liquid's `{% raw %}` is also relevant though I don't know how confused vimwiki might get seeing the liquid syntax.

**Comment by chipsenkbeil** [comment]
> Well, good news
> 
>     * Users can disable liquid on a per-file basis or change the global default
> 
>     * In the `next` branch, I plan to change the default for liquid to be off-by-default.  I got the idea from zola.  The theory is that layout needs Liquid's power but rarely does a page body need Liquid's power.  This would greatly speed up processing.

That **is** good to know 😄 Is parsing a major slowdown today? For vimwiki, it's using nom and after some tweaks I managed to get it to be equal or better to pandoc. For the largest file I've had available to test (several thousand lines). Does cobalt support multi-threaded rendering to spread out the rendering of files?

> Liquid's `{% raw %}` is also relevant though I don't know how confused vimwiki might get seeing the liquid syntax.

For the vimwiki parser, it should skip over that as normal text. But that's assuming you're rendering vimwiki to html before processing liquid templates. I would have assumed you'd process liquid syntax in one pass and then go over the output with the markdown (or vimwiki) parser next. Is it different?

**Comment by epage** [comment]
> That is good to know 😄 Is parsing a major slowdown today?

I've not profiled things to pin point the slowest parts but liquid does have its overhead (its not the easiest template language to optimize).  I'd like to be competitive with the other SSG when processing 5000+ files :). This doesn't mean we can't have features but more so that we balance convenience/performance when choosing defaults.

> Does cobalt support multi-threaded rendering to spread out the rendering of files?

Not yet but that is part of the `next` work.

> I would have assumed you'd process liquid syntax in one pass and then go over the output with the markdown (or vimwiki) parser next. Is it different?

We do templating (liquid) before markup (markdown). I was more so checking for understanding on how vimwiki would behave in vim since I assume one of the benefits of supporting vimwiki would be the Vim integration.

**Comment by chipsenkbeil** [comment]
> I've not profiled things to pin point the slowest parts but liquid does have its overhead (its not the easiest template language to optimize). I'd like to be competitive with the other SSG when processing 5000+ files :). This doesn't mean we can't have features but more so that we balance convenience/performance when choosing defaults.

File IO, text processing, etc. would be one of the slower aspects. I haven't done any recent profiling of the vimwiki crate since I got it to be onpar with pandoc. If that becomes an issue, it can be revisited.

> Not yet but that is part of the next work.

Great 🎉 

> We do templating (liquid) before markup (markdown). I was more so checking for understanding on how vimwiki would behave in vim since I assume one of the benefits of supporting vimwiki would be the Vim integration.

To my knowledge nothing special happens. I haven't checked how the vimwiki plugin's html output would be impacted, but that shouldn't matter here since you wouldn't be using the plugin to do that. No special syntax highlighting gets applied, no concealment, etc.

I'm also working to expand vimwiki's support to other editors beyond vim through the efforts in vimwiki-rs and its companion server, but I'm not there yet.

**Comment by epage** [comment]
> File IO, text processing, etc. would be one of the slower aspects. I haven't done any recent profiling of the vimwiki crate since I got it to be onpar with pandoc. If that becomes an issue, it can be revisited.

I'm not worried about vimwiki's performance since people choose to pay for that performance and if a profiler says its a problem, we can look into it.

**Comment by chipsenkbeil** [comment]
@epage, as a heads up, I'm almost done with the support to convert vimwiki to html. Once that's in place, hoping to revisit adding vimwiki support here in the next couple of weeks. May be closer to end of May timeframe depending on my bandwidth.

**Comment by chipsenkbeil** [comment]
Almost done as an overstatement at the time, but now I'm close and hoping to cut the first stable release by end of this coming week.

@epage I glanced at the source of cobalt again where the markdown conversion happens. [`RenderContext`](https://github.com/cobalt-org/cobalt.rs/blob/d905914556db619e83f2779fcbcafd0e234a5de6/src/document.rs#L24) contains a markdown model. Is this where I'd write a simplistic vimwiki model? Or is this something that should be abstracted?

**Comment by epage** [comment]
Go ahead and add it there for now.  I am wrapping up the core work on `typos` and am redirecting my focus to `cobalt` and will be playing with how to change the architecture up.
