### ISSUE TITLE
use cover images for a blog ?

### ISSUE THREAD

**Issue by gurugeek** [cobalt-org/cobalt.rs#853]
Hello and first of all thanks a lot for Cobalt! is a really simple yet great static site generator. I am attempting to port a blog to cobalt and I was wondering about the easier way to add a custom tag cover: that would take a url parameter to load a cover image.

thanks in advance for your help.

**Comment by epage** [comment]
A hacky way to do this is to create a cover snippet that you `include`.  


Some options for the future:
- User-defined tags, see https://github.com/cobalt-org/cobalt.rs/issues/779
- Tera like macros, https://github.com/cobalt-org/liquid-rust/issues/322
- Tera like filters, https://github.com/cobalt-org/liquid-rust/issues/321

**Comment by gurugeek** [comment]
thanks a lot much appreciated.
