### ISSUE TITLE
Integratting Clippy

### ISSUE THREAD

**Issue by achernyak** [cobalt-org/cobalt.rs#87]
Have you thought about integrating [Clippy](https://github.com/Manishearth/rust-clippy) into the project to normalize the coding style?

I just tried it out on my fork and it found a bunch of things that could be corrected. I would be open to working through them and getting it integrated if you like the idea.

**Comment by LucioFranco** [comment]
We actually use clippy in `cobalt-org/liquid-rust` so I don't see a reason we couldn't use it here. let's see what @johannhof says.

**Comment by johannhof** [comment]
Yes, good idea! Note that we have a setup in liquid-rust (at the top of lib.rs) that makes the build fail on nightly when certain rules are violated, for CI. It would be neat to have something like that in Cobalt as well, but we can also do that as a follow-up.

Thanks!

**Comment by johannhof** [comment]
@achernyak did you get the chance to work on this yet? I'd love to see Clippy integrated as the code base grows :)

**Comment by achernyak** [comment]
@johannhof I actually got this integrated, in a branch and was able to solve most the issues, but the main building function needs a major refactor. 

Maybe I could update it with the latest changes and push up what I have so we can discuss the best path forward.

**Comment by johannhof** [comment]
Sounds good!

**Comment by johannhof** [comment]
@achernyak any update on this? :)

**Comment by johannhof** [comment]
Closed by 1c039da3508f23937833c42e16771ebbe499eb28
