### ISSUE TITLE
Cobalt injecting inline CSS into `<pre>` and `<pre>`'s `<span>` HTML tags

### ISSUE THREAD

**Issue by papojari** [cobalt-org/cobalt.rs#887]
Cobalt is injecting inline CSS into `<pre>` and `<pre>`'s `<span>` HTML tags when building my site regarding the color and background color. This is annoying because it overrides my stylesheets options for the `<pre>` tag.

An example part of a `<pre>` tag:

```
<pre style="background-color:#2b303b;"><span style="color:#c0c5ce;">Font Awesome Free License</span><span style="color:#c0c5ce;">-------------------------</span><span style="color:#c0c5ce;"></span><span style="color:#c0c5ce;">Font Awesome Free is free, open source, and GPL friendly. You can use it for</span>
```

**Comment by epage** [comment]
Could you post a link to your site souce/output or provide a sample of what your source looks like that was generated from this?

This looks like syntax highlighting, which you get when you do code fences.  You can disable syntax highlighting in your [`_cobalt.yml` file](https://cobalt-org.github.io/docs/config/)

**Comment by papojari** [comment]
@epage I can't currently test if it is because of syntax highlighting (it's on). My page source is [here](https://codeberg.org/papojari/pages-cobalt). I'll make another comment in a few days when I have tested if disabling syntax highlighting fixes it.

**Comment by papojari** [comment]
Disabling syntax highlighting did fix the problem. Thank you.
