### ISSUE TITLE
cobalt build creates extra build artifacts when destination is inside project

### ISSUE THREAD

**Issue by lcowell** [cobalt-org/cobalt.rs#900]
Specifying a destination directory inside the project root where the name is not prefixed with `_` results in additional nested copies of the site content.

When you don't specify a directory and build, we get one build, as expected.

```
[ -d _site ] && rm -r ./_site
cobalt build
# _site is updated
cobalt build
# _site is updated and no additional subdirectories are created
```

When specifying a directory inside the project, we get an additional nesting of the build content each time we build.

```
[ -d public ] && rm -r ./public
cobalt build -d public
# public now exists with the expected contents
cobalt build -d public
# public/public now exists
cobalt build -d public
# public/public/public now exists
```

`cobalt build -d _site` does what you'd expect
`cobalt build -d ../_site` does what you'd expect
`cobalt build -d ../public` does what you'd expect

Possibly related to #833

**Comment by epage** [comment]
Sorry, this fell through the cracks.  It looks to specifically be a bug with `-d`.  I've got a fix incoming.
