### ISSUE TITLE
Can't link to headings

### ISSUE THREAD

**Issue by papojari** [cobalt-org/cobalt.rs#902]
It'd like to be able to link to headings like this:

# example

```HTML
<a href="index.html/#example">example</a>
```
Therefore when HTML is generated from markdown, an id would have to be added to every heading:

```HTML
<h1 id="example">example</h1>
```  
It'd be nice if this was the default. Otherwise you could add an option in the configuration file.

**Comment by epage** [comment]
Yes.  We've got this as #559
