### ISSUE TITLE
Can't make a draft in the `_drafts` directory

### ISSUE THREAD

**Issue by pixilcode** [cobalt-org/cobalt.rs#915]
I've just made a new project. In my _cobalt.yml, I have:

```yaml
site:
  title: cobalt blog
  description: Blog Posts Go Here
  base_url: http://example.com
posts:
  rss: rss.xml
  drafts_dir: _drafts
```
(I added the line `drafts_dir` in an attempt to solve the following problem, though it didn't work)

I'd like to make a draft of a post, which will be stored in the draft directory `_drafts` (where the [documentation](https://cobalt-org.github.io/docs/directory/) says they can be stored). However, when I attempt to create a new post draft there, I get the following error.

```
$ cobalt new "Study Journal: Sept. 3, 2021" --file _drafts
Error: new command failed
Info: caused by Could not create `Study Journal: Sept. 3, 2021`
Info: caused by Target file wouldn't be a member of any collection: /directory/of/source/_drafts/study-journal-sept-3-2021.md
```

How can I create a draft post in the `_drafts` directory? (I'd like to keep them seperated from the posts)

**Comment by epage** [comment]
I assume you are using v0.16.5?  Looks like this is fixed in `master`.  I'll try to get a release out soon.
