### ISSUE TITLE
Crash when creating a new blog post

### ISSUE THREAD

**Issue by Newbytee** [cobalt-org/cobalt.rs#917]
I'm not sure what I did to reproduce this exactly, but it happened earlier today. Cobalt would crash whenever I ran `cobalt new` in a freshly created blog. Backtrace: [cobalt-crash.txt](https://github.com/cobalt-org/cobalt.rs/files/7211514/cobalt-crash.txt)

**Comment by epage** [comment]
```
  15:     0x5595501d2903 - core::result::unwrap_failed::h7047a123950875be
                               at /builddir/build/BUILD/rustc-1.55.0-src/library/core/src/result.rs:1599:5
  16:     0x55955035f655 - cobalt::args::get_config::hb2d756c7b0ad5814
  17:     0x55955034c03a - cobalt::new::new_command::hfd308009428d6717
  18:     0x559550334287 - cobalt::main::h74f06b9bf20f7ee9
```

Did it print any messages with it?  I'm not seeing any `unwrap` calls but I do see an `expect` which would print "How does this fail?".  That `expect` is from trying to look up the current working directory.

**Comment by Newbytee** [comment]
That was the full log (you can see I included the command invocation at the top to make that clearer). Maybe I just had managed to end up in a nonexistent working directory somehow. I'll report back when I'm on my laptop again.

**Comment by epage** [comment]
Oh. missed that, thanks!

It does intrigue me that *someone* ran into this and maybe I should actually gracefully fail.
