### ISSUE TITLE
Can't 'include' a snippet

### ISSUE THREAD

**Issue by pixilcode** [cobalt-org/cobalt.rs#925]
Thanks so much for this project first off!

I have at the top level of the site a file 'index.liquid'. I'd like to include a header snippet, which I currently have in a directory 'snippets'. This is a piece of what 'index.liquid' looks like:

```liquid
<html lang="en">
<head>...</head>
<body>
  {% include "header" %}
  ...
</body>
</html>
```

I would expect this to insert the contents of 'snippets/header.liquid' into the file. However, when I run `cobalt serve`, it gives me the error:

```
Error: serve command failed
Info: caused by Failed to render content for index.html
Info: caused by liquid: Unknown partial-template
  with:
    requested partial=snippets/header.liquid
    available partials=
from: {% include "snippets/header.liquid" %}
```

(I have also tried `"snippets/header"` and `"header"`, which both give me almost the same error).

What can I do to include the header snippet into my liquid template?

**Comment by pixilcode** [comment]
As I was doing more research on the website, I found my answer [here](https://cobalt-org.github.io/docs/directory/). It turns out, the directory where liquid snippets should be put is `_includes`. :sweat_smile:

**Comment by epage** [comment]
Oh, sorry I hadn't gotten to this yet! Glad you found the answer. What could we have done to make discovering it faster / easier?
