### ISSUE TITLE
Docs.rs documentation fails for 0.17

### ISSUE THREAD

**Issue by elpiel** [cobalt-org/cobalt.rs#940]
It seems that the latest successful build was for version 0.16.5

See the error on: https://docs.rs/crate/cobalt-bin/0.17.4

Here is the build log of docs.rs:

https://docs.rs/crate/cobalt-bin/0.17.0/builds/435188

**Comment by epage** [comment]
Thanks for letting me know!

That is quite strange that big int is failing when CI normally passes.
