### ISSUE TITLE
Add mustache-style templating option

### ISSUE THREAD

**Issue by 0xc0000007b** [cobalt-org/cobalt.rs#944]
Liquid is not ergonomic nor is it pleasing to the eyes. To gain acceptance with web developers please adopt mustache-style templating. I did a quick search and there's already a crate for it: https://crates.io/crates/bart

**Comment by 0xc0000007b** [comment]
After tooling around with VSCode snippets for a while I'm satisfied with Liquid. Plus there's plenty of Jekyll examples and other doc. Still not a huge fan but I'd rather see pagination added than pile issues on you.

**Comment by epage** [comment]
On top of this, static site generators tend to be coupled to their template engine.  We could add support for another language but it would be bolted on and significantly slower.  It'd require a large justification.  We are unlikely to replace liquid as its what people expect from this project.
