### ISSUE TITLE
Include sass

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/cobalt.rs#99]
It would be cool to support SASS. https://github.com/compass-rs/sass-rs

**Comment by flosse** [comment]
+1

**Comment by epage** [comment]
With #278, this is mostly resolved.  The main outstanding issue is making this a default-enabled feature.

One major reason it isn't is that its failing to work with windows-gnu target. 

There is a small concern on my side about dynamically linking on Linux/Mac (I think this is what it currently does) rather than statically linking (no runtime deps).

**Comment by Geobert** [comment]
if we decide to make MSVC toolchain as mandatory for windows, we can close this. with the GNU toolchain, it's miniz that does not work.

**Comment by epage** [comment]
Yup, as I mentioned above, the concerns are
- Doesn't work with windows-gnu.
  - I'm unsure how important the windows-gnu target is for potential contributors / users which is why I haven't made a decision on that.
- Dynamically links on Mac/Linux.
  - There has been a desire for Cobalt to have only the basic dependencies.  So this depends on how commonly available libsass is.

**Comment by Geobert** [comment]
Oh I see, I missed the dynamically linking part ^^

**Comment by Geobert** [comment]
For the gnu target, I'd say, let's disable it until someone need it?

**Comment by epage** [comment]
Discussion in #180 is leading towards dropping windows-gnu. :(

**Comment by Geobert** [comment]
Can we close this one now?

**Comment by epage** [comment]
While we dropped the problematic targets, we never made sass a default feature

See https://github.com/cobalt-org/cobalt.rs/blob/master/Cargo.toml#L67

**Comment by Geobert** [comment]
Oh yeah, true. Why? Lack of testing?

**Comment by epage** [comment]
Looking above in the comments, the main remaining concern is that libsass is dynamically linked on Mac/Linux and I am concerned about making cobalt have install requirements.

**Comment by Geobert** [comment]
Need to check how gutenberg is doing it, they claim a no dynamic dependency policy

**Comment by pickfire** [comment]
I tried it out with continuous deployment on https://github.com/FUTUREHACKmy/futurehackmy.github.io/tree/9438d72716a3e8ed916ca2fc9ee724282afac230 but then not sure how to include the sass as well.

**Comment by Geobert** [comment]
Uh, for some reason, I can't compile sass anymore, need to investigate :(

**Comment by Geobert** [comment]
For sass, I had this error:
```
error: failed to run custom build command for `sass-sys v0.4.3`
process didn't exit successfully: `I:\Dev\cobalt.rs\target\debug\build\sass-sys-cda42525225dc0fb\build-script-build` (exit code: 101)
--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at 'Build error:
STDERR:
STDOUT:Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 03/02/2018 12:01:45.
Project "C:\Users\Geob\.cargo\registry\src\github.com-1ecc6299db9ec823\sass-sys-0.4.3\libsass\win\libsass.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Win64".
Project "C:\Users\Geob\.cargo\registry\src\github.com-1ecc6299db9ec823\sass-sys-0.4.3\libsass\win\libsass.sln" (1) is building "C:\Users\Geob\.cargo\registry\src\github.com-1ecc6299db9ec823\sass-sys-0.4.3\libsass\win\libsass.vcxproj" (2) on node 1 (default targets).
GitVersion:
  git -C .. describe --abbrev=4 --dirty --always --tags
C:\Users\Geob\.cargo\registry\src\github.com-1ecc6299db9ec823\sass-sys-0.4.3\libsass\win\libsass.vcxproj(10,5): warning : fatal: Not a git repository (or any of the parent directories): .git
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
C:\Users\Geob\.cargo\registry\src\github.com-1ecc6299db9ec823\sass-sys-0.4.3\libsass\win\libsass.vcxproj(10,5): warning MSB3073: The command "git -C .. describe --abbrev=4 --dirty --always --tags" exited with code 128.
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  Build continuing because "ContinueOnError" on the task "Exec" is set to "true".
Main:
  libsass:
  Building Static LibSass
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Geob\.cargo\registry\src\github.com-1ecc6299db9ec823\sass-sys-0.4.3\libsass\win\libsass.vcxproj]
Done Building Project "C:\Users\Geob\.cargo\registry\src\github.com-1ecc6299db9ec823\sass-sys-0.4.3\libsass\win\libsass.vcxproj" (default targets) -- FAILED. Done Building Project "C:\Users\Geob\.cargo\registry\src\github.com-1ecc6299db9ec823\sass-sys-0.4.3\libsass\win\libsass.sln" (default targets) -- FAILED.
```

But I managed to compile it by installing VS community, open the sln, accept the upgrade of the project to toolset v140, close VS, cargo build.

needed this as well: `call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"`

**Comment by Keats** [comment]
> Dynamically links on Mac/Linux. 

It's statically linked on all platforms: https://github.com/compass-rs/sass-rs/blob/master/sass-sys/build.rs#L57

**Comment by epage** [comment]
Looks like this is now resolved even if it is still a pain on Windows.
